"""A class representing a measure space."""

from __future__ import annotations

from functools import cached_property
from typing import TYPE_CHECKING, Literal

import numpy as np

from ..sigma_algebras.sigma_algebra import SigmaAlgebraMethods

if TYPE_CHECKING:
    from collections.abc import Hashable

    from ...typing.measure_domain import MeasureDomain
    from ..measures.measure import Measure
    from ..measures.probability_measure import ProbabilityMeasure
    from ..sigma_algebras import SigmaAlgebra
    from .domain import Domain
    from .measurable_space import MeasurableSpace
    from .probability_space import ProbabilitySpace
    from .set import Set


class MeasureSpace(SigmaAlgebraMethods):
    r"""A class representing a measure space.

    See the Notes section below for the mathematical details.

    Parameters
    ----------
    domain : Domain | IndexLike | None, default=None
        The domain of the measure space.
    sig_alg : SigmaAlgebra | None, default=None
        The sigma-algebra of the measure space.
    measure : Measure | None, default=None
        The measure of the measure space.

    Examples
    --------
    >>> from sigalg.core import Domain, Measure, MeasureSpace, SigmaAlgebra

    Build a `MeasureSpace` object with only a domain. The power-set sigma-algebra and counting measure will be generated by default.

    >>> X = Domain.from_sequence(size=3)
    >>> measure_space = MeasureSpace(domain=X)
    >>> print(measure_space)  # doctest: +NORMALIZE_WHITESPACE
    Measure space (X, R, C)
    =======================
    <BLANKLINE>
    * Domain 'X':
     x
     0
     1
     2
    <BLANKLINE>
    * Sigma algebra 'R':
         R
    x
    0    0
    1    1
    2    2
    <BLANKLINE>
    * Measure 'C':
          C
    x
    0     1
    1     1
    2     1

    Create a measure space with a custom sigma-algebra and measure.

    >>> F = SigmaAlgebra(
    ...     domain=X,
    ...     mapping={
    ...         0: 0,
    ...         1: 1,
    ...         2: 1,
    ...     },
    ... )
    >>> mu = Measure(
    ...     domain=F,
    ...     mapping={
    ...         0: 1,
    ...         1: 2,
    ...     },
    ... )
    >>> measure_space = MeasureSpace(domain=X, sig_alg=F, measure=mu)
    >>> print(measure_space)  # doctest: +NORMALIZE_WHITESPACE
    Measure space (X, F, mu)
    ========================
    <BLANKLINE>
    * Domain 'X':
     x
     0
     1
     2
    <BLANKLINE>
    * Sigma algebra 'F':
         F
    x
    0    0
    1    1
    2    1
    <BLANKLINE>
    * Measure 'mu':
            mu
    F
    0        1
    1        2

    The same measure space as the latter one may be created with only the measure as an explicit parameter. The sigma-algebra of the measure space is automatically extracted from the measure, and the domain is automatically extracted from the sigma-algebra. Thus, the minimal amount of information needed to construct a `MeasureSpace` object is just the measure.

    >>> measure_space = MeasureSpace(measure=mu)
    >>> print(measure_space)  # doctest: +NORMALIZE_WHITESPACE
    Measure space (X, F, mu)
    ========================
    <BLANKLINE>
    * Domain 'X':
        x
        0
        1
        2
    <BLANKLINE>
    * Sigma algebra 'F':
            F
    x
    0    0
    1    1
    2    1
    <BLANKLINE>
    * Measure 'mu':
            mu
    F
    0        1
    1        2

    Notes
    -----
    A *measure space* is a triple $(X, \mathcal{F}, \mu)$ consisting of a nonempty set $X$, a $\sigma$-algebra $\mathcal{F}$ on $X$, and a measure $\mu$ defined on $\mathcal{F}$.
    """

    _repr_name = "MeasureSpace"
    _str_name = "Measure space"

    # --------------------- constructors --------------------- #

    def __init__(
        self,
        domain: Domain | None = None,
        sig_alg: SigmaAlgebra | None = None,
        measure: Measure | None = None,
    ) -> None:
        from ..measures.probability_measure import ProbabilityMeasure
        from .probability_space import ProbabilitySpace

        if measure is not None:
            if sig_alg is None or measure.sig_alg == sig_alg:
                sig_alg = measure.sig_alg
            else:
                raise ValueError(
                    "If both the measure and sigma-algebra are given, the sigma-algebra of the former must equal the latter."
                )

            if domain is not None and sig_alg.domain != domain:
                raise ValueError(
                    "If both the measure and the domain are given, the domain of the sigma-algebra of the former must equal the latter."
                )

        elif sig_alg is not None:
            measure = type(self)._default_measure(sig_alg)

            if domain is not None and sig_alg.domain != domain:
                raise ValueError(
                    "If both the sigma-algebra and the domain are given, the domain of the former must equal the latter."
                )

        elif domain is not None:
            measure = type(self)._default_measure(domain)

        self.measure = measure

        if isinstance(measure, ProbabilityMeasure):
            self.__class__ = ProbabilitySpace

    @classmethod
    def _from_validated(cls, *, measure: Measure) -> MeasureSpace:
        from ..measures.probability_measure import ProbabilityMeasure
        from ..spaces.probability_space import ProbabilitySpace

        measure_space = object.__new__(cls)
        measure_space.measure = measure

        if isinstance(measure, ProbabilityMeasure):
            measure_space.__class__ = ProbabilitySpace

        return measure_space

    @classmethod
    def _default_measure(
        cls,
        domain: MeasureDomain = None,
    ) -> Measure:
        from ..measures.measure import Measure

        return Measure.counting(domain=domain)

    @classmethod
    def from_set(
        cls,
        subset: Set,
        measure: Measure,
        normalize: bool = False,
    ) -> MeasureSpace:
        r"""Create a measure space from a measurable set.

        See the Notes section below for the mathematical details.

        Parameters
        ----------
        subset : Set
            The subset on which to create the measure space
        measure : Measure
            The measure to use for the measure space.
        normalize : bool, default=False
            Whether to normalize the measure to create a probability space.

        Returns
        -------
        set_measure_space : MeasureSpace
            A new measure space built from the measurable set.

        Examples
        --------
        >>> from sigalg.core import Domain, Measure, MeasureSpace, SigmaAlgebra

        Define a measure space.

        >>> X = Domain.from_sequence(size=6)
        >>> F = SigmaAlgebra(
        ...     domain=X,
        ...     mapping={
        ...         0: 0,
        ...         1: 1,
        ...         2: 1,
        ...         3: 2,
        ...         4: 2,
        ...         5: 0,
        ...     },
        ... )
        >>> mu = Measure(
        ...     domain=F,
        ...     mapping={
        ...         0: 1,
        ...         1: 2,
        ...         2: 3,
        ...     },
        ... )
        >>> measure_space = MeasureSpace(X, F, mu)

        Extract a subset from the sigma-algebra of the measure space, and build a measure space from it. The sigma-algebra and measure of the new measure space are just the restrictions of the original ones.

        >>> A = measure_space.get_set([1, 2, 3, 4])
        >>> set_space = MeasureSpace.from_set(A, mu)
        >>> print(set_space)  # doctest: +NORMALIZE_WHITESPACE
        Measure space (A, F|A, mu|A)
        ============================
        <BLANKLINE>
        * Domain 'A':
         x
         1
         2
         3
         4
        <BLANKLINE>
        * Sigma algebra 'F|A':
           F|A
        x
        1    1
        2    1
        3    2
        4    2
        <BLANKLINE>
        * Measure 'mu|A':
                mu|A
        F
        1          2
        2          3

        Now, create a new measure space from the same set, but normalize the measure to create a probability space.

        >>> conditional_space = MeasureSpace.from_set(A, mu, normalize=True)
        >>> print(conditional_space)  # doctest: +NORMALIZE_WHITESPACE
        Probability space (A, F|A, mu|A)
        ================================
        <BLANKLINE>
        * Domain 'A':
         x
         1
         2
         3
         4
        <BLANKLINE>
        * Sigma algebra 'F|A':
           F|A
        x
        1    1
        2    1
        3    2
        4    2
        <BLANKLINE>
        * Probability measure 'mu|A':
                 mu|A
        F
        1         0.4
        2         0.6

        Notes
        -----
        Let $A$ be a nonempty measurable set in a measure space $(X,\mathcal{F},\mu)$. We may create a measure space $(A,\mathcal{F}_A,\mu_A)$ where $\mathcal{F}_A$ is the $\sigma$-algebra consisting of all $B\in \mathcal{F}$ with $B\subset A$, and $\mu_A$ is the measure on $\mathcal{F}_A$ defined so that $\mu_A(B) = \mu(B)$.

        Provided that $\mu(A) \neq 0$, we may replace $\mu_A$ with $\mu_A/\mu(A)$ and then $(A,\mathcal{F}_A,\mu_A/\mu(A))$ is a probability space.
        """
        from ..measures.measure import Measure
        from .set import Set

        if not isinstance(subset, Set):
            raise TypeError("subset must be a Set instance.")
        if not isinstance(measure, Measure):
            raise TypeError("measure must be a Measure instance.")
        if subset not in measure.sig_alg:
            raise ValueError(
                "The subset must be in the sigma-algebra of the given measure."
            )

        restricted_measure = measure.restrict_to(subset, normalize=normalize)

        return cls._from_validated(measure=restricted_measure)

    @classmethod
    def from_rand(
        cls,
        domain_size: int,
        domain_dim: int = 1,
        domain_range: tuple[int, int] | None = None,
        domain_variable_names: list[Hashable] | None = None,
        domain_name: Hashable | None = None,
        num_atoms: int = 1,
        sig_alg_dim: int = 1,
        atom_ID_range: tuple[int, int] | None = None,
        sig_alg_variable_names: list[Hashable] | None = None,
        num_null_atoms: int = 0,
        sig_alg_name: Hashable = "F",
        measure_distribution: Literal["uniform", "poisson", "dirichlet"] = "uniform",
        measure_max_value: int = 10,
        measure_rate: float = 5.0,
        measure_name: Hashable | None = None,
        random_state: int | np.random.Generator | None = None,
    ) -> MeasureSpace:
        """Generate a random measure space.

        Parameters
        ----------
        domain_size : int
            The number of points in the domain of the measure space.
        domain_dim : int, default=1
            The dimension of the sample space.
        domain_range : tuple[int, int] | None, default=None
            The range of values for the sample space. If `None`, the sample space values will be drawn from the range [0, domain_size).
        domain_variable_names : list[Hashable] | None, default=None
            The variable names for the sample space.
        domain_name : Hashable | None, default=None
            The name of the sample space.
        num_atoms : int, default=1
            The number of atoms in the sigma-algebra of the measure space.
        sig_alg_dim : int, default=1
            The dimension of the sigma-algebra.
        atom_ID_range : tuple[int, int] | None, default=None
            The range of atom IDs. If `None`, the atom IDs will be drawn from the range [0, num_atoms).
        sig_alg_variable_names : list[Hashable] | None, default=None
            The variable names for the sigma-algebra.
        num_null_atoms : int, default=0
            The number of null atoms in the sigma-algebra.
        sig_alg_name : Hashable, default="F"
            The name of the sigma-algebra.
        measure_distribution : Literal["uniform", "poisson", "dirichlet], default="uniform"
            The distribution from which to draw the values of the measure. If `uniform`, the values are drawn from the set of integers in `[measure_min_value, measure_max_value)`; if `poisson`, the values are drawn from a Poisson distribution with rate equal to `measure_rate`; if `dirichlet`, the values are drawn from a Dirichlet distribution with concentration parameters equal to `1`, producing a probability measure.
        measure_min_value : int, default=1
            The minimum value for `uniform` measure distribution.
        measure_max_value : int, default=10
            The maximum value for the `uniform` measure distribution.
        measure_rate : float, default=5.0
            The rate parameter for the `poisson` measure distribution.
        measure_name : Hashable | None, default=None
            The name of the measure.
        random_state : int | np.random.Generator | None, default=None
            The random state for reproducibility.

        Returns
        -------
        measure_space : MeasureSpace
            A new randomly generated measure space with the specified parameters.

        Examples
        --------
        >>> from sigalg.core import MeasureSpace

        Generate a random measure space with a 1-dimensional domain containing five points, sigma-algebra with 1-dimensional atom IDs and three atoms, and a measure with values drawn randomly from the integers in the (default) interval `[1,10)`.

        >>> measure_space = MeasureSpace.from_rand(
        ...     domain_size=5,
        ...     num_atoms=3,
        ...     random_state=42,
        ... )
        >>> print(measure_space)  # doctest: +NORMALIZE_WHITESPACE
        Measure space (X, F, mu)
        ========================
        <BLANKLINE>
        * Domain 'X':
        x
        4
        1
        0
        3
        2
        <BLANKLINE>
        * Sigma algebra 'F':
        F
        x
        4  1
        1  1
        0  0
        3  1
        2  2
        <BLANKLINE>
        * Measure 'mu':
        mu
        F
        1   5
        0   5
        2   4

        Now, suppose we draw the measure values from a Dirichlet distribution. This will produce a random probability space.

        >>> prob_space = MeasureSpace.from_rand(
        ...     domain_size=5,
        ...     num_atoms=3,
        ...     measure_distribution="dirichlet",
        ...     random_state=42,
        ... )
        >>> print(prob_space)  # doctest: +NORMALIZE_WHITESPACE
        Probability space (Omega, F, P)
        ===============================
        <BLANKLINE>
        * Sample space 'Omega':
        omega
            4
            1
            0
            3
            2
        <BLANKLINE>
        * Sigma algebra 'F':
            F
        omega
        4      1
        1      1
        0      0
        3      1
        2      2
        <BLANKLINE>
        * Probability measure 'P':
                P
        F
        1  0.598912
        0  0.024366
        2  0.376722

        Now, we generate a random measure space with a 4-dimensional sample space of cardinality 10 with custom variable names, a sigma-algebra with 5 atoms and 2-dimensional identifiers with custom names, and a measure with values drawn from a Poisson distribution with (default) rate parameter `5.0`.

        >>> measure_space = MeasureSpace.from_rand(
        ...     domain_size=10,
        ...     domain_dim=4,
        ...     domain_variable_names=["x", "y", "z", "w"],
        ...     num_atoms=5,
        ...     sig_alg_dim=2,
        ...     sig_alg_variable_names=["A", "B"],
        ...     measure_distribution="poisson",
        ...     random_state=42,
        ... )
        >>> print(measure_space)  # doctest: +NORMALIZE_WHITESPACE
        Measure space (X, F, mu)
        ========================
        <BLANKLINE>
        * Domain 'X':
         x  y  z  w
         2  8  4  5
         9  3  1  9
         1  7  6  4
         6  8  5  4
         3  4  2  0
         8  5  8  0
         5  8  8  2
         7  6  1  7
         4  7  3  0
         0  9  4  8
        <BLANKLINE>
        * Sigma algebra 'F':
        i        0  1
        x y z w
        2 8 4 5  3  3
        9 3 1 9  4  3
        1 7 6 4  4  3
        6 8 5 4  1  4
        3 4 2 0  2  2
        8 5 8 0  2  2
        5 8 8 2  0  0
        7 6 1 7  4  3
        4 7 3 0  4  3
        0 9 4 8  2  2
        <BLANKLINE>
        * Measure 'mu':
             mu
        A B
        3 3   8
        4 3   5
        1 4   1
        2 2   8
        0 0   7
        """
        from ..measures.measure import Measure
        from ..sigma_algebras.sigma_algebra import SigmaAlgebra
        from .domain import Domain
        from .probability_space import ProbabilitySpace
        from .sample_space import SampleSpace

        if random_state is not None and not isinstance(
            random_state, (int, np.random.Generator)
        ):
            raise TypeError(
                "random_state must be an integer, np.random.Generator, or None."
            )

        rng = (
            random_state
            if isinstance(random_state, np.random.Generator)
            else np.random.default_rng(random_state)
        )

        domain_class = Domain

        if cls is ProbabilitySpace or measure_distribution == "dirichlet":
            measure_name = measure_name if measure_name else "P"
            measure_distribution = "dirichlet"
            domain_class = SampleSpace

        domain = domain_class.from_rand(
            size=domain_size,
            dim=domain_dim,
            sample_range=domain_range,
            variable_names=domain_variable_names,
            name=domain_name,
            random_state=rng,
        )

        sig_alg = SigmaAlgebra.from_rand(
            domain=domain,
            num_atoms=num_atoms,
            dim=sig_alg_dim,
            atom_ID_range=atom_ID_range,
            variable_names=sig_alg_variable_names,
            random_state=rng,
            name=sig_alg_name,
        )
        measure = Measure.from_rand(
            domain=sig_alg,
            num_null_atoms=num_null_atoms,
            distribution=measure_distribution,
            max_value=measure_max_value,
            rate=measure_rate,
            name=measure_name,
            random_state=rng,
        )

        return cls(domain, sig_alg, measure)

    # --------------------- properties --------------------- #

    @cached_property
    def measurable_space(self) -> MeasurableSpace:
        """Get the measurable space of the measure space.

        Returns
        -------
        measurable_space : MeasurableSpace
            The measurable space of the measure space.

        Examples
        --------
        >>> from sigalg.core import Domain, Measure, MeasureSpace, SigmaAlgebra
        >>> X = Domain.from_sequence(size=3)
        >>> F = SigmaAlgebra(
        ...     domain=X,
        ...     mapping={
        ...         0: 0,
        ...         1: 1,
        ...         2: 1,
        ...     },
        ... )
        >>> mu = Measure(
        ...     domain=F,
        ...     mapping={
        ...         0: 1,
        ...         1: 2,
        ...     },
        ... )
        >>> measure_space = MeasureSpace(domain=X, sig_alg=F, measure=mu)
        >>> print(measure_space.measurable_space)  # doctest: +NORMALIZE_WHITESPACE
        Measurable space (X, F)
        =======================
        <BLANKLINE>
        * Domain 'X':
         x
         0
         1
         2
        <BLANKLINE>
        * Sigma algebra 'F':
           F
        x
        0  0
        1  1
        2  1
        """
        from .measurable_space import MeasurableSpace

        if self.sig_alg is not None:
            return MeasurableSpace._from_validated(sig_alg=self.sig_alg)
        else:
            return None

    @cached_property
    def domain(self) -> Domain | None:
        """Get the domain of the measure space.

        Returns
        -------
        domain : Domain | None
            The domain of the measure space.

        Examples
        --------
        Define a measure space and print it.

        >>> from sigalg.core import Domain, Measure, MeasureSpace, SigmaAlgebra
        >>> X = Domain.from_sequence(size=4)
        >>> F = SigmaAlgebra(
        ...     domain=X,
        ...     mapping={
        ...         0: 0,
        ...         1: 1,
        ...         2: 2,
        ...         3: 2,
        ...     },
        ... )
        >>> mu = Measure(
        ...     domain=F,
        ...     mapping={
        ...         0: 2,
        ...         1: 3,
        ...         2: 5,
        ...     },
        ... )
        >>> measure_space = MeasureSpace(X, F, mu)
        >>> print(measure_space.domain)  # doctest: +NORMALIZE_WHITESPACE
        Domain 'X':
         x
         0
         1
         2
         3
        """
        return self.sig_alg.domain if self.measure is not None else None

    @cached_property
    def sig_alg(self) -> SigmaAlgebra | None:
        """Get the sigma-algebra of the measure space.

        Returns
        -------
        sig_alg : SigmaAlgebra
            The sigma-algebra of the measure space.

        Examples
        --------
        Define a measure space and print it.

        >>> from sigalg.core import Domain, Measure, MeasureSpace, SigmaAlgebra
        >>> X = Domain.from_sequence(size=4)
        >>> F = SigmaAlgebra(
        ...     domain=X,
        ...     mapping={
        ...         0: 0,
        ...         1: 1,
        ...         2: 2,
        ...         3: 2,
        ...     },
        ... )
        >>> mu = Measure(
        ...     domain=F,
        ...     mapping={
        ...         0: 2,
        ...         1: 3,
        ...         2: 5,
        ...     },
        ... )
        >>> measure_space = MeasureSpace(X, F, mu)
        >>> print(measure_space.sig_alg)  # doctest: +NORMALIZE_WHITESPACE
        Sigma algebra 'F':
           F
        x
        0  0
        1  1
        2  2
        3  2
        """
        return self.measure.sig_alg if self.measure is not None else None

    # --------------------- conversion methods --------------------- #

    def to_prob_space(
        self,
        measure: ProbabilityMeasure | None = None,
        in_place: bool = False,
    ) -> ProbabilitySpace | None:
        """Convert the measure space to a probability space.

        Parameters
        ----------
        measure : ProbabilityMeasure | None, default=None
            The probability measure to use for the conversion. If not provided, the current measure will be used if it is a probability measure; otherwise, a uniform probability measure will be created on the current sigma-algebra.
        in_place : bool, default=False
            If `True`, convert the current measure space to a probability space in place. If `False`, return a new `ProbabilitySpace` instance without modifying the current measure space.

        Returns
        -------
        prob_space: ProbabilitySpace | None
            If `in_place` is `False`, returns a new `ProbabilitySpace` instance. If `in_place` is `True`, returns `None` and modifies the current measure space to become a `ProbabilitySpace`.

        Examples
        --------
        Create a measure space with a non-probability measure.

        >>> from sigalg.core import Domain, Measure, MeasureSpace, ProbabilityMeasure, SigmaAlgebra
        >>> X = Domain.from_sequence(size=3)
        >>> F = SigmaAlgebra(
        ...     domain=X,
        ...     mapping={
        ...         0: 0,
        ...         1: 0,
        ...         2: 1,
        ...     },
        ... )
        >>> mu = Measure(
        ...     domain=F,
        ...     mapping={
        ...         0: 1,
        ...         1: 2,
        ...     },
        ... )
        >>> measure_space = MeasureSpace(X, F, mu)

        Promote to a probability space. The measure `mu` will be replaced with the uniform probability measure on the sigma-algebra.

        >>> prob_space = measure_space.to_prob_space()
        >>> print(prob_space)  # doctest: +NORMALIZE_WHITESPACE
        Probability space (X, F, U)
        ===========================
        <BLANKLINE>
        * Domain 'X':
         x
         0
         1
         2
        <BLANKLINE>
        * Sigma algebra 'F':
             F
        x
        0    0
        1    0
        2    1
        <BLANKLINE>
        * Probability measure 'U':
                U
        F
        0     0.5
        1     0.5

        Define a probability measure and promote the measure space to a probability space using that measure.

        >>> P = ProbabilityMeasure(
        ...     domain=F,
        ...     mapping={
        ...         0: 0.2,
        ...         1: 0.8,
        ...     },
        ... )
        >>> prob_space = measure_space.to_prob_space(measure=P)
        >>> print(prob_space)  # doctest: +NORMALIZE_WHITESPACE
        Probability space (X, F, P)
        ===========================
        <BLANKLINE>
        * Domain 'X':
         x
         0
         1
         2
        <BLANKLINE>
        * Sigma algebra 'F':
             F
        x
        0    0
        1    0
        2    1
        <BLANKLINE>
        * Probability measure 'P':
                P
        F
        0     0.2
        1     0.8
        """
        from ..measures.probability_measure import ProbabilityMeasure
        from .probability_space import ProbabilitySpace

        if measure is not None:
            if not isinstance(measure, ProbabilityMeasure):
                raise ValueError("If given, measure must be a probability measure.")
        else:
            if not isinstance(self.measure, ProbabilityMeasure):
                if np.abs(self.measure.data.sum() - 1) < 1e-8:
                    measure = ProbabilityMeasure(
                        domain=self.sig_alg,
                        mapping=self.measure.data.rename("probability"),
                        name=self.measure.name,
                    )
                else:
                    measure = ProbabilityMeasure.uniform(domain=self.sig_alg)

            else:
                measure = self.measure

        if in_place:
            self.measure = measure
            self.__class__ = ProbabilitySpace
            return None
        else:
            return ProbabilitySpace(self.domain, self.sig_alg, measure)

    # --------------------- methods --------------------- #

    def is_subspace(self, other: MeasureSpace) -> bool:
        r"""Check if this measure space is a subspace of another measure space.

        See the Notes section below for the mathematical details.

        Parameters
        ----------
        other : MeasureSpace
            The other measure space to compare with.

        Returns
        -------
        is_subspace : bool
            `True` if this measure space is a subspace of the other measure space, `False` otherwise.

        Examples
        --------
        Define a measure space that will serve as a subspace of another.

        >>> from sigalg.core import (
        ...     Domain,
        ...     Measure,
        ...     MeasureSpace,
        ...     SigmaAlgebra,
        ... )
        >>> X = Domain.from_sequence(size=4)
        >>> F = SigmaAlgebra(
        ...     domain=X,
        ...     mapping={
        ...         0: 0,
        ...         1: 0,
        ...         2: 1,
        ...         3: 1,
        ...     },
        ... )
        >>> mu = Measure(
        ...     domain=F,
        ...     mapping={
        ...         0: 4,
        ...         1: 6,
        ...     },
        ... )
        >>> sub_space = MeasureSpace(X, F, mu)

        Define a measure space that will serve as the superspace.

        >>> G = SigmaAlgebra(
        ...     domain=X,
        ...     mapping={
        ...         0: 0,
        ...         1: 0,
        ...         2: 1,
        ...         3: 2,
        ...     },
        ...     name="G",
        ... )
        >>> nu = Measure(
        ...     domain=G,
        ...     mapping={
        ...         0: 4,
        ...         1: 4,
        ...         2: 2,
        ...     },
        ... )

        Check the sub- and super-space relations.

        >>> super_space = MeasureSpace(X, G, nu)
        >>> print(sub_space.is_subspace(super_space))
        True
        >>> print(super_space.is_subspace(sub_space))
        False

        Notes
        -----
        A measure space $(X, \mathcal{F}, \mu)$ is a *subspace* of another measure space $(X, \mathcal{G}, \nu)$ if $\mathcal{F} \subseteq \mathcal{G}$ and $\mu$ is the restriction of $\nu$ to $\mathcal{F}$. In other words, every set in $\mathcal{F}$ is also a set in $\mathcal{G}$, and the measure assigned to each set in $\mathcal{F}$ by $\mu$ is the same as the measure assigned to that set by $\nu$ when restricted to $\mathcal{F}$.
        """
        if not isinstance(other, MeasureSpace):
            raise TypeError("other must be a MeasureSpace instance.")

        try:
            is_sub_alg = self.sig_alg <= other.sig_alg
        except ValueError:
            return False

        if not is_sub_alg:
            return False
        elif self.measure != other.measure.restrict_to(self.sig_alg):
            return False
        else:
            return True

    def get_random_set(
        self,
        num_atoms: int,
        is_null: bool = False,
        name: Hashable = "A",
        random_state: int | np.random.Generator | None = None,
    ) -> Set:
        """Get a random measurable (possibly null) set consisting of a specified number of atoms.

        Parameters
        ----------
        num_atoms : int
            The number of atoms to include in the random measurable set. If `is_null` is `True`, `num_atoms` will be reset to the minimum of `num_atoms` and the number of null atoms in the measure space.
        is_null : bool, default=False
            If `True`, the random set will be a null set.
        name : Hashable, default="A"
            Name identifier for the set.
        random_state : int | np.random.Generator | None, default=None
            The random state for reproducibility.

        Returns
        -------
        random_set : MeasurableSet
            A random measurable set consisting of the specified number of atoms. If `is_null` is `True`, the set will be a null set.
        """
        return self.measure.get_random_set(
            num_atoms=num_atoms,
            is_null=is_null,
            name=name,
            random_state=random_state,
        )

    def __lt__(self, other: MeasureSpace) -> bool:
        """Check whether this measure space is a proper subspace of another.

        Calls `is_subspace`. Check the docstring there for more details.
        """
        return self.is_subspace(other) and self != other

    def __le__(self, other: MeasureSpace) -> bool:
        """Check whether this measure space is a subspace of another.

        Calls `is_subspace`. Check the docstring there for more details.
        """
        return self.is_subspace(other)

    def __gt__(self, other: MeasureSpace) -> bool:
        """Check whether this measure space is a proper superspace of another.

        Calls `is_subspace`. Check the docstring there for more details.
        """
        return other.is_subspace(self) and self != other

    def __ge__(self, other: MeasureSpace) -> bool:
        """Check whether this measure space is a superspace of another.

        Calls `is_subspace`. Check the docstring there for more details.
        """
        return other.is_subspace(self)

    # --------------------- data access methods --------------------- #

    def __iter__(self):
        """Allow unpacking of measure space components.

        Enables syntax like: `X, F, mu = measure_space`, where `X` is the domain of the measure space, and `F` and `mu` are its sigma-algebra and measure, respectively.

        Yields
        ------
        domain : Domain
            The domain.
        sig_alg : SigmaAlgebra
            The sigma-algebra.
        measure : Measure
            The measure.

        Examples
        --------
        >>> from sigalg.core import Domain, Measure, MeasureSpace, SigmaAlgebra
        >>> X = Domain.from_sequence(size=3)
        >>> F = SigmaAlgebra(
        ...     domain=X,
        ...     mapping={
        ...         0: 0,
        ...         1: 1,
        ...         2: 1,
        ...     },
        ... )
        >>> mu = Measure(
        ...     domain=F,
        ...     mapping={
        ...         0: 0.5,
        ...         1: 0.5,
        ...     },
        ... )
        >>> measure_space = MeasureSpace(domain=X, sig_alg=F, measure=mu)
        >>> X1, F1, mu1 = measure_space
        >>> print(X1)  # doctest: +NORMALIZE_WHITESPACE
        Domain 'X':
         x
         0
         1
         2
        >>> print(F1)  # doctest: +NORMALIZE_WHITESPACE
        Sigma algebra 'F':
           F
        x
        0  0
        1  1
        2  1
        >>> print(mu1)  # doctest: +NORMALIZE_WHITESPACE
        Measure 'mu':
                 mu
        F
        0       0.5
        1       0.5
        """
        yield self.domain
        yield self.sig_alg
        yield self.measure

    # --------------------- equality --------------------- #

    def __eq__(self, other: object) -> bool:
        """Check equality with another measure space.

        Two measure spaces are equal if they have the same domain,
        sigma-algebra, and measure.

        Parameters
        ----------
        other : object
            Another object to compare with.

        Returns
        -------
        is_equal : bool
            `True` if the other object is a `MeasureSpace` with identical
            components, `False` otherwise.
        """
        if not isinstance(other, MeasureSpace):
            return False
        return (
            self.domain == other.domain
            and self.sig_alg == other.sig_alg
            and self.measure == other.measure
        )

    # --------------------- representation --------------------- #

    def __repr__(self) -> str:
        """Return a concise string representation of the measure space.

        Returns
        -------
        repr_str : str
            A string representation showing the measure space's component names.
        """
        if self.domain is None or self.sig_alg is None or self.measure is None:
            return type(self)._repr_name + "(empty)"
        return (
            type(self)._repr_name + f"(domain={self.domain.name}, "
            f"sig_alg={self.sig_alg.name}, "
            f"measure={self.measure.name})"
        )

    def __str__(self) -> str:
        """Return a detailed string representation of the measure space.

        Returns
        -------
        repr_str : str
            A formatted string showing the measure space header and detailed
            representations of its components.
        """
        if self.domain is None or self.sig_alg is None or self.measure is None:
            return f"Measure space '{self.name}': empty"
        header = (
            f"{type(self)._str_name} ("
            f"{self.domain.name}, "
            f"{self.sig_alg.name}, "
            f"{self.measure.name})"
        )
        separator = "=" * len(header)
        return (
            header
            + "\n"
            + separator
            + "\n\n* "
            + str(self.domain)
            + "\n\n* "
            + str(self.sig_alg)
            + "\n\n* "
            + str(self.measure)
        )

    # --------------------- validation methods --------------------- #

    @staticmethod
    def _validate_parameters(
        domain: Domain | None,
        sig_alg: SigmaAlgebra | None,
        measure: Measure | None,
    ) -> None:
        """Validate measure space construction parameters.

        Parameters
        ----------
        domain : Domain | None
            The domain to validate.
        sig_alg : SigmaAlgebra | None
            The sigma-algebra to validate.
        measure : Measure | None
            The measure to validate.
        """
        from ..measures import Measure
        from ..sigma_algebras import SigmaAlgebra
        from .domain import Domain

        if domain is not None and not isinstance(domain, Domain):
            raise TypeError("domain must be a Domain instance.")
        if sig_alg is not None and not isinstance(sig_alg, SigmaAlgebra):
            raise TypeError("sig_alg must be a SigmaAlgebra instance.")
        if measure is not None and not isinstance(measure, Measure):
            raise TypeError("measure must be a Measure instance.")

        if sig_alg is not None and measure is not None:
            if not (measure.sig_alg <= sig_alg) and not (measure.sig_alg > sig_alg):
                raise ValueError(
                    "If both sig_alg and measure are given, the measure must be defined on either a super- or sub-sigma-algebra of the given sigma-algebra."
                )

        if domain is not None:
            if sig_alg is not None and sig_alg.domain != domain:
                raise ValueError(
                    "If sig_alg is given, its domain must match the given domain."
                )
