"""A class representing a probability space."""

from __future__ import annotations

from collections.abc import Hashable
from typing import TYPE_CHECKING

import numpy as np
import pandas as pd

from ..measures.probability_measure import ProbabilityMeasureMethods
from ..sigma_algebras.sigma_algebra import SigmaAlgebraMethods

if TYPE_CHECKING:
    from ..measures import ProbabilityMeasure
    from ..sigma_algebras import SigmaAlgebra
    from .measurable_set import MeasurableSet
    from .sample_space import SampleSpace


class MeasureSpace(SigmaAlgebraMethods, ProbabilityMeasureMethods):
    r"""A class representing a probability space.

    See the Notes section below for the mathematical details.

    If all three of `sample_space`, `sig_alg`, and `prob_measure` are provided, the `sample_space` of the provided `sig_alg` must match the provided `sample_space`, and the `sig_alg` of the provided `prob_measure` must match the provided `sig_alg`. Otherwise, if only some of the parameters are provided, the missing components will be automatically created to be compatible with the provided ones as follows:

    * If `sample_space` is not provided but `sig_alg` or `prob_measure` is given, then `sample_space` will be taken from the provided `sig_alg` or `prob_measure`.
    * If `sig_alg` is not provided but `sample_space` or `prob_measure` is given, then `sig_alg` will be set to the power set sigma-algebra on the provided `sample_space` (if given) or the sigma-algebra of the provided `prob_measure` (if given).
    * If `prob_measure` is not provided but `sample_space` or `sig_alg` is given, then `prob_measure` will be set to the uniform probability measure on the provided `sig_alg` (if given) or the power set sigma-algebra on the provided `sample_space` (if given).

    If none of the parameters are provided, all components will be initialized to `None` and can be set later.

    Parameters
    ----------
    sample_space : SampleSpace | None, default=None
        The sample space of the probability space.
    sig_alg : SigmaAlgebra | None, default=None
        The sigma-algebra of the probability space.
    prob_measure : ProbabilityMeasure | None, default=None
        The probability measure of the probability space.

    Examples
    --------
    Build a `MeasureSpace` object with only a sample space. The power-set sigma-algebra and uniform probability measure will be generated by default.

    >>> from sigalg.core import ProbabilityMeasure, MeasureSpace, SampleSpace, SigmaAlgebra
    >>> Omega = SampleSpace.from_sequence(size=3)
    >>> prob_space = MeasureSpace(sample_space=Omega)
    >>> print(prob_space)  # doctest: +NORMALIZE_WHITESPACE
    Probability space (Omega, power_set, U)
    =======================================
    <BLANKLINE>
    * Sample space 'Omega':
     sample
          0
          1
          2
    <BLANKLINE>
    * Sigma algebra 'power_set':
            atom_ID
    sample
    0             0
    1             1
    2             2
    <BLANKLINE>
    * Probability measure 'U':
            probability
    sample
    0          0.333333
    1          0.333333
    2          0.333333

    Create a probability space with a custom sigma-algebra and probability measure

    >>> F = SigmaAlgebra(
    ...     sample_space=Omega,
    ...     mapping={
    ...         0: 0,
    ...         1: 1,
    ...         2: 1,
    ...     },
    ... )
    >>> P = ProbabilityMeasure(
    ...     sig_alg=F,
    ...     mapping={
    ...         0: 0.5,
    ...         1: 0.5,
    ...     },
    ... )
    >>> prob_space = MeasureSpace(sample_space=Omega, sig_alg=F, prob_measure=P)
    >>> print(prob_space)  # doctest: +NORMALIZE_WHITESPACE
    Probability space (Omega, F, P)
    ===============================
    <BLANKLINE>
    * Sample space 'Omega':
     sample
          0
          1
          2
    <BLANKLINE>
    * Sigma algebra 'F':
            atom_ID
    sample
    0             0
    1             1
    2             1
    <BLANKLINE>
    * Probability measure 'P':
             probability
    atom_ID
    0                0.5
    1                0.5

    Notes
    -----
    A *probability space* is a triple $(\Omega, \mathcal{F}, P)$ consisting of a sample space $\Omega$, a $\sigma$-algebra $\mathcal{F}$ on $\Omega$, and a probability measure $P$ defined on $\mathcal{F}$.
    """

    # --------------------- constructors --------------------- #

    def __init__(
        self,
        sample_space: SampleSpace | None = None,
        sig_alg: SigmaAlgebra | None = None,
        prob_measure: ProbabilityMeasure | None = None,
    ) -> None:
        self._validate_parameters(sample_space, sig_alg, prob_measure)
        self._sample_space, self._sig_alg, self._prob_measure = (
            self._generate_components(sample_space, sig_alg, prob_measure)
        )

    def _generate_components(self, sample_space, sig_alg, prob_measure):
        from ..measures.probability_measure import ProbabilityMeasure
        from ..sigma_algebras.sigma_algebra import SigmaAlgebra

        parameter_cases = (
            sample_space is not None,
            sig_alg is not None,
            prob_measure is not None,
        )

        if parameter_cases in [(0, 0, 1), (0, 1, 0), (0, 1, 1)]:
            sample_space = (
                prob_measure.sample_space
                if prob_measure is not None
                else sig_alg.sample_space
            )
            if parameter_cases in [(0, 0, 1)]:
                sig_alg = prob_measure.sig_alg
            if parameter_cases in [(0, 1, 0)]:
                prob_measure = ProbabilityMeasure.uniform(sig_alg)
        if parameter_cases == (1, 0, 0):
            sig_alg = SigmaAlgebra.power_set(sample_space)
            prob_measure = ProbabilityMeasure.uniform(sig_alg)
        if parameter_cases == (1, 0, 1):
            sig_alg = prob_measure.sig_alg
        if parameter_cases == (1, 1, 0):
            prob_measure = ProbabilityMeasure.uniform(sig_alg)

        return sample_space, sig_alg, prob_measure

    @classmethod
    def from_event(
        cls,
        event: MeasurableSet,
        prob_measure: ProbabilityMeasure | None = None,
    ) -> MeasureSpace:
        r"""Create a conditional probability space from an event.

        See the Notes section below for the mathematical details.

        Parameters
        ----------
        event : MeasurableSet
            The event on which to create the conditional probability space.
        prob_measure : ProbabilityMeasure | None, default=None
            The probability measure to use for the conditional probability space. If `None`, the probability measure carried by `event` will be used.

        Raises
        ------
        TypeError
            If `event` is not an `MeasurableSet` instance or `prob_measure` is not a `ProbabilityMeasure` instance (if given).
        ValueError
            If the event is not in the domain (sigma-algebra) of the probability measure, or if the probability of the event under the given probability measure is zero.

        Returns
        -------
        prob_space : MeasureSpace
            A new probability space representing the conditional probability space on the event.

        Examples
        --------
        Construct a probability space.

        >>> from sigalg.core import ProbabilityMeasure, MeasureSpace, SampleSpace, SigmaAlgebra
        >>> Omega = SampleSpace.from_sequence(size=6)
        >>> F = SigmaAlgebra(
        ...     sample_space=Omega,
        ...     mapping={
        ...         0: 0,
        ...         1: 1,
        ...         2: 1,
        ...         3: 2,
        ...         4: 2,
        ...         5: 0,
        ...     },
        ... )
        >>> P = ProbabilityMeasure(
        ...     sig_alg=F,
        ...     mapping={
        ...         0: 0.13,
        ...         1: 0.55,
        ...         2: 0.32,
        ...     },
        ... )
        >>> prob_space = MeasureSpace(Omega, F, P)

        Extract an event from the probability space and form the conditional probability space.

        >>> A = prob_space.get_event([1, 2, 3, 4])
        >>> conditional_space = MeasureSpace.from_event(event=A)
        >>> print(conditional_space)  # doctest: +NORMALIZE_WHITESPACE
        Probability space (A, F_A, P_A)
        ===============================
        <BLANKLINE>
        * Sample space 'A':
         sample
              1
              2
              3
              4
        <BLANKLINE>
        * Sigma algebra 'F_A':
                atom_ID
        sample
        1             1
        2             1
        3             2
        4             2
        <BLANKLINE>
        * Probability measure 'P_A':
                 probability
        atom_ID
        1           0.632184
        2           0.367816

        Notes
        -----
        Let $A$ be an event in a probability space $(\Omega,\mathcal{F},P)$. Provided that $A$ has positive probability, we may construct a *conditional probability space* $(A, \mathcal{F}_A, P_A)$ as follows. The $\sigma$-algebra $\mathcal{F}_A$ contains those sets of the form $A\cap B$, for $B\in \mathcal{F}$. The probability measure $P_A$ is defined on events $E\in \mathcal{F}_A$ by setting $P_A(E) = P(E)/P(A)$.

        Provided that $\Omega$ is finite (as it always is, in SigAlg), then the $\sigma$-algebra $\mathcal{F}_A$ is determined uniquely by its atoms, which are just the nonempty intersections of the atoms of $\mathcal{F}$ with $A$. Thus, the same atom identifiers from $\mathcal{F}$ can be used to define $\mathcal{F}_A$.
        """
        from ..measures.probability_measure import ProbabilityMeasure
        from ..sigma_algebras.sigma_algebra import SigmaAlgebra
        from .measurable_set import MeasurableSet

        if not isinstance(event, MeasurableSet):
            raise TypeError("event must be an MeasurableSet instance.")
        if prob_measure is not None and not isinstance(
            prob_measure, ProbabilityMeasure
        ):
            raise TypeError(
                "prob_measure must be a ProbabilityMeasure instance, if given."
            )
        if prob_measure is None:
            prob_measure = event.prob_measure
        if event not in prob_measure.sig_alg:
            raise ValueError(
                "The event must be in the domain (sigma-algebra) of the given probability measure."
            )

        prob_event = prob_measure(event)
        sig_alg = prob_measure.sig_alg
        event_sample_space = event.to_sample_space()

        if prob_event < 1e-8:
            raise ValueError(
                "Cannot create a probability space from an event with 0 probability."
            )

        event_atom_ids = {omega: sig_alg.sample_id_to_atom_id[omega] for omega in event}
        event_sig_alg_name = f"{sig_alg.name}_{event.name}"
        event_sigma_algebra = SigmaAlgebra(
            sample_space=event_sample_space,
            mapping=event_atom_ids,
            name=event_sig_alg_name,
        )

        atom_event_indicator = (
            (
                pd.concat([event.indicator.data, sig_alg.data], axis=1)
                .drop_duplicates()
                .set_index("atom_ID")
            )
            .squeeze(axis=1)
            .astype(bool)
        )

        atom_probs = (prob_measure.data[atom_event_indicator] / prob_event).to_dict()
        event_prob_measure_name = f"{prob_measure.name}_{event.name}"
        event_probability_measure = ProbabilityMeasure(
            sig_alg=event_sigma_algebra,
            mapping=atom_probs,
            name=event_prob_measure_name,
        )

        return cls(
            sample_space=event_sample_space,
            sig_alg=event_sigma_algebra,
            prob_measure=event_probability_measure,
        )

    @classmethod
    def from_rand(
        cls,
        sample_space_size: int,
        num_atoms: int,
        sample_space_dim: int = 1,
        sig_alg_dim: int = 1,
        sample_space_range: tuple[int, int] | None = None,
        atom_ID_range: tuple[int, int] | None = None,
        sample_space_variable_names: list[Hashable] | None = None,
        sig_alg_variable_names: list[Hashable] | None = None,
        random_state: int | np.random.Generator | None = None,
        sample_space_name: Hashable = "Omega",
        sig_alg_name: Hashable = "F",
        prob_measure_name: Hashable = "P",
    ) -> MeasureSpace:
        """Generate a random probability space.

        Parameters
        ----------
        sample_space_size : int
            The number of sample points in the sample space.
        num_atoms : int
            The number of atoms in the sigma-algebra.
        sample_space_dim : int, default=1
            The dimensionality of the sample space.
        sig_alg_dim : int, default=1
            The dimensionality of the sigma-algebra.
        sample_space_range : tuple[int, int] | None, default=None
            The range of values for the sample space. If `None`, the sample space values will be drawn from the range [0, sample_space_size).
        atom_ID_range : tuple[int, int] | None, default=None
            The range of atom IDs. If `None`, the atom IDs will be drawn from the range [0, num_atoms).
        sample_space_variable_names : list[Hashable] | None, default=None
            The variable names for the sample space.
        sig_alg_variable_names : list[Hashable] | None, default=None
            The variable names for the sigma-algebra.
        random_state : int | np.random.Generator | None, default=None
            The random state for reproducibility.
        sample_space_name : Hashable, default="Omega"
            The name of the sample space.
        sig_alg_name : Hashable, default="F"
            The name of the sigma-algebra.
        prob_measure_name : Hashable, default="P"
            The name of the probability measure.

        Raises
        ------
        TypeError
            If `random_state` is not an integer, `np.random.Generator`, or `None`.

        Returns
        -------
        prob_space : MeasureSpace
            A new randomly generated probability space with the specified parameters.

        Examples
        --------
        >>> from sigalg.core import MeasureSpace
        >>> prob_space = MeasureSpace.from_rand(
        ...     sample_space_size=10,
        ...     num_atoms=5,
        ...     sample_space_dim=4,
        ...     sig_alg_dim=2,
        ...     sample_space_range=(2, 23),
        ...     atom_ID_range=(1, 10),
        ...     sample_space_variable_names=["x", "y", "z", "w"],
        ...     sig_alg_variable_names=["A", "B"],
        ...     random_state=42,
        ... )
        >>> print(prob_space)  # doctest: +NORMALIZE_WHITESPACE
        Probability space (Omega, F, P)
        ===============================
        <BLANKLINE>
        * Sample space 'Omega':
         x  y  z  w
        19 11 12  9
        12  5 21 18
         3 15 10 19
        11 13 11 11
         8  6  3 13
        17 20  3 20
        15 19  7 15
        22  5 17 16
         6  9  3 22
        16 11 20 16
        <BLANKLINE>
        * Sigma algebra 'F':
                    atom_ID
        x  y  z  w
        19 11 12 9   (5, 9)
        12 5  21 18  (4, 7)
        3  15 10 19  (4, 7)
        11 13 11 11  (2, 4)
        8  6  3  13  (9, 7)
        17 20 3  20  (9, 7)
        15 19 7  15  (3, 7)
        22 5  17 16  (4, 7)
        6  9  3  22  (4, 7)
        16 11 20 16  (9, 7)
        <BLANKLINE>
        * Probability measure 'P':
            probability
        A B
        5 9     0.225175
        4 7     0.276163
        2 4     0.215250
        9 7     0.268911
        3 7     0.014500
        """
        from ..measures.probability_measure import ProbabilityMeasure
        from ..sigma_algebras.sigma_algebra import SigmaAlgebra
        from .sample_space import SampleSpace

        if random_state is not None and not isinstance(
            random_state, (int, np.random.Generator)
        ):
            raise TypeError(
                "random_state must be an integer, np.random.Generator, or None."
            )

        rng = (
            random_state
            if isinstance(random_state, np.random.Generator)
            else np.random.default_rng(random_state)
        )

        sample_space = SampleSpace.from_rand(
            size=sample_space_size,
            dim=sample_space_dim,
            sample_range=sample_space_range,
            variable_names=sample_space_variable_names,
            random_state=rng,
            name=sample_space_name,
        )
        sig_alg = SigmaAlgebra.from_rand(
            num_atoms=num_atoms,
            sample_space=sample_space,
            dim=sig_alg_dim,
            atom_ID_range=atom_ID_range,
            variable_names=sig_alg_variable_names,
            random_state=rng,
            name=sig_alg_name,
        )
        prob_measure = ProbabilityMeasure.from_rand(
            sig_alg=sig_alg,
            random_state=rng,
            name=prob_measure_name,
        )

        return cls(sample_space, sig_alg, prob_measure)

    # --------------------- properties --------------------- #

    @property
    def sample_space(self) -> SampleSpace | None:
        """Get the sample space of the probability space.

        The `sample_space` parameter is settable. If the probability space is not empty, the new sample space must contain the same number of sample points as the current sample space, and the sigma-algebra and probability measure will be updated to be defined on the new sample space with the same atom structure and probabilities as before. If the probability space is empty, then setting the sample space will set the sigma-algebra to be the power set sigma-algebra on the new sample space, and the probability measure to be the uniform probability measure on that sigma-algebra.

        Returns
        -------
        sample_space : SampleSpace | None
            The sample space of the probability space.

        Examples
        --------
        Define a probability space and print it.

        >>> from sigalg.core import ProbabilityMeasure, MeasureSpace, SampleSpace, SigmaAlgebra
        >>> Omega = SampleSpace.from_sequence(size=4)
        >>> F = SigmaAlgebra(
        ...     sample_space=Omega,
        ...     mapping={
        ...         0: 0,
        ...         1: 1,
        ...         2: 2,
        ...         3: 2,
        ...     },
        ... )
        >>> P = ProbabilityMeasure(
        ...     sig_alg=F,
        ...     mapping={
        ...         0: 0.2,
        ...         1: 0.3,
        ...         2: 0.5,
        ...     },
        ... )
        >>> prob_space = MeasureSpace(Omega, F, P)
        >>> print(prob_space)  # doctest: +NORMALIZE_WHITESPACE
        Probability space (Omega, F, P)
        ===============================
        <BLANKLINE>
        * Sample space 'Omega':
         sample
              0
              1
              2
              3
        <BLANKLINE>
        * Sigma algebra 'F':
                atom_ID
        sample
        0             0
        1             1
        2             2
        3             2
        <BLANKLINE>
        * Probability measure 'P':
                 probability
        atom_ID
        0                0.2
        1                0.3
        2                0.5

        Set the `sample_space` property to a new sample space.

        >>> S = SampleSpace(["a", "b", "c", "d"], name="S")
        >>> prob_space.sample_space = S
        >>> print(prob_space)  # doctest: +NORMALIZE_WHITESPACE
        Probability space (S, F, P)
        ===========================
        <BLANKLINE>
        * Sample space 'S':
        sample
            a
            b
            c
            d
        <BLANKLINE>
        * Sigma algebra 'F':
                atom_ID
        sample
        a             0
        b             1
        c             2
        d             2
        <BLANKLINE>
        * Probability measure 'P':
                 probability
        atom_ID
        0                0.2
        1                0.3
        2                0.5

        Instantiate an empty `MeasureSpace` instance and set its sample space afterward. Notice the default sigma-algebra and probability measure that are created.

        >>> empty_prob_space = MeasureSpace()
        >>> empty_prob_space.sample_space = S
        >>> print(empty_prob_space)  # doctest: +NORMALIZE_WHITESPACE
        Probability space (S, power_set, U)
        ===================================
        <BLANKLINE>
        * Sample space 'S':
        sample
            a
            b
            c
            d
        <BLANKLINE>
        * Sigma algebra 'power_set':
            atom_ID
        sample
        a            a
        b            b
        c            c
        d            d
        <BLANKLINE>
        * Probability measure 'U':
                probability
        sample
        a              0.25
        b              0.25
        c              0.25
        d              0.25
        """
        return self._sample_space

    @sample_space.setter
    def sample_space(self, sample_space: SampleSpace) -> None:
        """Set the sample space of the probability space.

        If the probability space is not empty, the new sample space must contain the same number of sample points as the current sample space, and the sigma-algebra and probability measure will be updated to be defined on the new sample space with the same atom structure and probabilities as before. If the probability space is empty, then setting the sample space will set the sigma-algebra to be the power set sigma-algebra on the new sample space, and the probability measure to be the uniform probability measure on that sigma-algebra.

        Parameters
        ----------
        sample_space : SampleSpace
            The new sample space to set.

        Raises
        ------
        TypeError
            If `sample_space` is not a `SampleSpace` instance.
        """
        from .sample_space import SampleSpace

        if not isinstance(sample_space, SampleSpace):
            raise TypeError("sample_space must be a SampleSpace instance.")

        if self.sample_space is not None:
            self.sig_alg.sample_space = sample_space
            self.prob_measure.sample_space = sample_space
            self._sample_space = sample_space
        else:
            self._sample_space, self._sig_alg, self._prob_measure = (
                self._generate_components(
                    sample_space=sample_space,
                    sig_alg=None,
                    prob_measure=None,
                )
            )

    @property
    def sig_alg(self) -> SigmaAlgebra | None:
        """Get the sigma-algebra of the probability space.

        The `sig_alg` parameter is settable. If the probability space is not empty, the new sigma-algebra must be a sub-sigma-algebra of the current sigma-algebra, and the probability measure will be updated to be the restriction of the current probability measure to the new sigma-algebra. If the probability space is empty, then setting the sigma-algebra will set the sample space to be the sample space of the new sigma-algebra, and the probability measure to be the uniform probability measure on the new sigma-algebra.

        Returns
        -------
        sig_alg : SigmaAlgebra
            The sigma-algebra of the probability space.

        Examples
        --------
        Define a probability space and print it.

        >>> from sigalg.core import ProbabilityMeasure, MeasureSpace, SampleSpace, SigmaAlgebra
        >>> Omega = SampleSpace.from_sequence(size=4)
        >>> F = SigmaAlgebra(
        ...     sample_space=Omega,
        ...     mapping={
        ...         0: 0,
        ...         1: 1,
        ...         2: 2,
        ...         3: 2,
        ...     },
        ... )
        >>> P = ProbabilityMeasure(
        ...     sig_alg=F,
        ...     mapping={
        ...         0: 0.2,
        ...         1: 0.3,
        ...         2: 0.5,
        ...     },
        ... )
        >>> prob_space = MeasureSpace(Omega, F, P)
        >>> print(prob_space)  # doctest: +NORMALIZE_WHITESPACE
        Probability space (Omega, F, P)
        ===============================
        <BLANKLINE>
        * Sample space 'Omega':
         sample
              0
              1
              2
              3
        <BLANKLINE>
        * Sigma algebra 'F':
                atom_ID
        sample
        0             0
        1             1
        2             2
        3             2
        <BLANKLINE>
        * Probability measure 'P':
                 probability
        atom_ID
        0                0.2
        1                0.3
        2                0.5

        Set the `sig_alg` property to a new sigma-algebra.

        >>> G = SigmaAlgebra(
        ...     sample_space=Omega,
        ...     mapping={
        ...         0: 0,
        ...         1: 1,
        ...         2: 1,
        ...         3: 1,
        ...     },
        ...     name="G",
        ... )
        >>> prob_space.sig_alg = G
        >>> print(prob_space)  # doctest: +NORMALIZE_WHITESPACE
        Probability space (Omega, G, P|G)
        =================================
        <BLANKLINE>
        * Sample space 'Omega':
         sample
              0
              1
              2
              3
        <BLANKLINE>
        * Sigma algebra 'G':
                atom_ID
        sample
        0             0
        1             1
        2             1
        3             1
        <BLANKLINE>
        * Probability measure 'P|G':
                 probability
        atom_ID
        0                0.2
        1                0.8

        Instantiate an empty `MeasureSpace` instance and set its sigma-algebra afterward. Notice the default sample space and probability measure that are created.

        >>> empty_prob_space = MeasureSpace()
        >>> empty_prob_space.sig_alg = G
        >>> print(empty_prob_space)  # doctest: +NORMALIZE_WHITESPACE
        Probability space (Omega, G, U)
        ===============================
        <BLANKLINE>
        * Sample space 'Omega':
         sample
              0
              1
              2
              3
        <BLANKLINE>
        * Sigma algebra 'G':
                atom_ID
        sample
        0             0
        1             1
        2             1
        3             1
        <BLANKLINE>
        * Probability measure 'U':
                 probability
        atom_ID
        0                0.5
        1                0.5
        """
        return self._sig_alg

    @sig_alg.setter
    def sig_alg(self, sig_alg: SigmaAlgebra) -> None:
        """Set the sigma-algebra of the probability space.

        If the probability space is not empty, the new sigma-algebra must be a sub-sigma-algebra of the current sigma-algebra, and the probability measure will be updated to be the restriction of the current probability measure to the new sigma-algebra. If the probability space is empty, then setting the sigma-algebra will set the sample space to be the sample space of the new sigma-algebra, and the probability measure to be the uniform probability measure on the new sigma-algebra.

        Parameters
        ----------
        sig_alg : SigmaAlgebra
            The new sigma-algebra to set.

        Raises
        ------
        TypeError
            If `sig_alg` is not a `SigmaAlgebra` instance.
        """
        from ..sigma_algebras.sigma_algebra import SigmaAlgebra

        if not isinstance(sig_alg, SigmaAlgebra):
            raise TypeError("sig_alg must be a SigmaAlgebra instance.")

        if self.sig_alg is not None:
            self.prob_measure.sig_alg = sig_alg
            self._sig_alg = sig_alg
        else:
            self._sample_space, self._sig_alg, self._prob_measure = (
                self._generate_components(
                    sample_space=None,
                    sig_alg=sig_alg,
                    prob_measure=None,
                )
            )

    @property
    def prob_measure(self) -> ProbabilityMeasure | None:
        """Get the probability measure of the probability space.

        The `prob_measure` parameter is settable. If the probability space is not empty, the new probability measure must be defined on a sub-sigma-algebra of the current sigma-algebra. The sigma-algebra will be updated to be the sigma-algebra of the new probability measure. If the probability space is empty, setting the probability measure will set the sample space to be the sample space of the new probability measure, and the sigma-algebra to be the sigma-algebra of the new probability measure.

        Returns
        -------
        prob : ProbabilityMeasure
            The probability measure of this probability space.

        Examples
        --------
        Define a probability space and print it.

        >>> from sigalg.core import ProbabilityMeasure, MeasureSpace, SampleSpace, SigmaAlgebra
        >>> Omega = SampleSpace.from_sequence(size=4)
        >>> F = SigmaAlgebra(
        ...     sample_space=Omega,
        ...     mapping={
        ...         0: 0,
        ...         1: 1,
        ...         2: 2,
        ...         3: 2,
        ...     },
        ... )
        >>> P = ProbabilityMeasure(
        ...     sig_alg=F,
        ...     mapping={
        ...         0: 0.2,
        ...         1: 0.3,
        ...         2: 0.5,
        ...     },
        ... )
        >>> prob_space = MeasureSpace(Omega, F, P)
        >>> print(prob_space)  # doctest: +NORMALIZE_WHITESPACE
        Probability space (Omega, F, P)
        ===============================
        <BLANKLINE>
        * Sample space 'Omega':
         sample
              0
              1
              2
              3
        <BLANKLINE>
        * Sigma algebra 'F':
                atom_ID
        sample
        0             0
        1             1
        2             2
        3             2
        <BLANKLINE>
        * Probability measure 'P':
                 probability
        atom_ID
        0                0.2
        1                0.3
        2                0.5

        Set the `prob_measure` property to a new probability measure.

        >>> G = SigmaAlgebra(
        ...     sample_space=Omega,
        ...     mapping={
        ...         0: 0,
        ...         1: 1,
        ...         2: 1,
        ...         3: 1,
        ...     },
        ...     name="G",
        ... )
        >>> Q = ProbabilityMeasure(
        ...     sig_alg=G,
        ...     mapping={
        ...         0: 0.5,
        ...         1: 0.5,
        ...     },
        ...     name="Q",
        ... )
        >>> prob_space.prob_measure = Q
        >>> print(prob_space)  # doctest: +NORMALIZE_WHITESPACE
        Probability space (Omega, G, Q)
        ===============================
        <BLANKLINE>
        * Sample space 'Omega':
         sample
              0
              1
              2
              3
        <BLANKLINE>
        * Sigma algebra 'G':
                atom_ID
        sample
        0             0
        1             1
        2             1
        3             1
        <BLANKLINE>
        * Probability measure 'Q':
                 probability
        atom_ID
        0                0.5
        1                0.5

        Instantiate an empty `MeasureSpace` instance and set its probability measure afterward. Notice the default sample space and sigma-algebra that are created.

        >>> empty_prob_space = MeasureSpace()
        >>> empty_prob_space.prob_measure = Q
        >>> print(empty_prob_space)  # doctest: +NORMALIZE_WHITESPACE
        Probability space (Omega, G, Q)
        ===============================
        <BLANKLINE>
        * Sample space 'Omega':
         sample
              0
              1
              2
              3
        <BLANKLINE>
        * Sigma algebra 'G':
                atom_ID
        sample
        0             0
        1             1
        2             1
        3             1
        <BLANKLINE>
        * Probability measure 'Q':
                 probability
        atom_ID
        0                0.5
        1                0.5
        """
        return self._prob_measure

    @prob_measure.setter
    def prob_measure(self, prob_measure: ProbabilityMeasure) -> None:
        """Set the probability measure of the probability space.

        If the probability space is not empty, the new probability measure must be defined on a sub-sigma-algebra of the current sigma-algebra. The sigma-algebra will be updated to be the sigma-algebra of the new probability measure. If the probability space is empty, setting the probability measure will set the sample space to be the sample space of the new probability measure, and the sigma-algebra to be the sigma-algebra of the new probability measure.

        Parameters
        ----------
        prob_measure : ProbabilityMeasure
            New probability measure.

        Raises
        ------
        TypeError
            If `prob_measure` is not a `ProbabilityMeasure` instance.
        """
        from ..measures.probability_measure import ProbabilityMeasure

        if not isinstance(prob_measure, ProbabilityMeasure):
            raise TypeError("prob_measure must be a ProbabilityMeasure instance.")

        if self.prob_measure is not None:
            self._sig_alg = prob_measure.sig_alg
            self._prob_measure = prob_measure
        else:
            self._sample_space, self._sig_alg, self._prob_measure = (
                self._generate_components(
                    sample_space=None,
                    sig_alg=None,
                    prob_measure=prob_measure,
                )
            )

    # --------------------- methods --------------------- #

    def is_subspace(self, other: MeasureSpace) -> bool:
        r"""Check if this probability space is a subspace of another probability space.

        See the Notes section below for the mathematical details.

        Parameters
        ----------
        other : MeasureSpace
            The other probability space to compare with.

        Raises
        ------
        TypeError
            If `other` is not a `MeasureSpace` instance.

        Returns
        -------
        is_subspace : bool
            `True` if this probability space is a subspace of the other probability space, `False` otherwise.

        Examples
        --------
        Define a probability space that will serve as a subspace of another.

        >>> from sigalg.core import (
        ...     ProbabilityMeasure,
        ...     MeasureSpace,
        ...     SampleSpace,
        ...     SigmaAlgebra,
        ... )
        >>> Omega = SampleSpace.from_sequence(size=4)
        >>> F = SigmaAlgebra(
        ...     sample_space=Omega,
        ...     mapping={
        ...         0: 0,
        ...         1: 0,
        ...         2: 1,
        ...         3: 1,
        ...     },
        ... )
        >>> P = ProbabilityMeasure(
        ...     sig_alg=F,
        ...     mapping={
        ...         0: 0.4,
        ...         1: 0.6,
        ...     },
        ... )
        >>> sub_space = MeasureSpace(Omega, F, P)

        Define a probability space that will serve as the superspace.

        >>> G = SigmaAlgebra(
        ...     sample_space=Omega,
        ...     mapping={
        ...         0: 0,
        ...         1: 0,
        ...         2: 1,
        ...         3: 2,
        ...     },
        ...     name="G",
        ... )
        >>> Q = ProbabilityMeasure(
        ...     sig_alg=G,
        ...     mapping={
        ...         0: 0.4,
        ...         1: 0.4,
        ...         2: 0.2,
        ...     },
        ... )

        Check the sub- and super-space relations.

        >>> super_space = MeasureSpace(Omega, G, Q)
        >>> print(sub_space.is_subspace(super_space))
        True
        >>> print(super_space.is_subspace(sub_space))
        False

        Notes
        -----
        A probability space $(\Omega, \mathcal{F}, P)$ is a *subspace* of another probability space $(\Omega, \mathcal{G}, Q)$ if $\mathcal{F} \subseteq \mathcal{G}$ and $P$ is the restriction of $Q$ to $\mathcal{F}$. In other words, every event in $\mathcal{F}$ is also an event in $\mathcal{G}$, and the probability assigned to each event in $\mathcal{F}$ by $P$ is the same as the probability assigned to that event by $Q$ when restricted to $\mathcal{F}$.
        """
        if not isinstance(other, MeasureSpace):
            raise TypeError("other must be a MeasureSpace instance.")

        try:
            is_sub_alg = self.sig_alg <= other.sig_alg
        except ValueError:
            return False

        if not is_sub_alg:
            return False
        elif self.prob_measure != other.prob_measure.restrict_to(
            sig_alg=self.sig_alg, in_place=False
        ):
            return False
        else:
            return True

    def __lt__(self, other: MeasureSpace) -> bool:
        """Check whether this probability space is a proper subspace of another.

        Calls `is_subspace`. Check the docstring there for more details.
        """
        return self.is_subspace(other) and self != other

    def __le__(self, other: MeasureSpace) -> bool:
        """Check whether this probability space is a subspace of another.

        Calls `is_subspace`. Check the docstring there for more details.
        """
        return self.is_subspace(other)

    def __gt__(self, other: MeasureSpace) -> bool:
        """Check whether this probability space is a proper superspace of another.

        Calls `is_subspace`. Check the docstring there for more details.
        """
        return other.is_subspace(self) and self != other

    def __ge__(self, other: MeasureSpace) -> bool:
        """Check whether this probability space is a superspace of another.

        Calls `is_subspace`. Check the docstring there for more details.
        """
        return other.is_subspace(self)

    # --------------------- data access methods --------------------- #

    def __iter__(self):
        """Allow unpacking of probability space components.

        Enables syntax like: `Omega, F, P = prob_space`, where `Omega` is the sample space of the probability space, and `F` and `P` are its sigma-algebra and probability measure, respectively.

        Yields
        ------
        sample_space : SampleSpace
            The sample space.
        sig_alg : SigmaAlgebra
            The sigma-algebra.
        prob_measure : ProbabilityMeasure
            The probability measure.

        Examples
        --------
        >>> from sigalg.core import ProbabilityMeasure, MeasureSpace, SampleSpace, SigmaAlgebra
        >>> Omega = SampleSpace.from_sequence(size=3)
        >>> F = SigmaAlgebra(
        ...     sample_space=Omega,
        ...     mapping={
        ...         0: 0,
        ...         1: 1,
        ...         2: 1,
        ...     },
        ... )
        >>> P = ProbabilityMeasure(
        ...     sig_alg=F,
        ...     mapping={
        ...         0: 0.5,
        ...         1: 0.5,
        ...     },
        ... )
        >>> prob_space = MeasureSpace(sample_space=Omega, sig_alg=F, prob_measure=P)
        >>> Omega1, F1, P1 = prob_space
        >>> print(Omega1)  # doctest: +NORMALIZE_WHITESPACE
        Sample space 'Omega':
         sample
              0
              1
              2
        >>> print(F1)  # doctest: +NORMALIZE_WHITESPACE
        Sigma algebra 'F':
                atom_ID
        sample
        0             0
        1             1
        2             1
        >>> print(P1)  # doctest: +NORMALIZE_WHITESPACE
        Probability measure 'P':
                 probability
        atom_ID
        0                0.5
        1                0.5
        """
        yield self.sample_space
        yield self.sig_alg
        yield self.prob_measure

    # --------------------- equality --------------------- #

    def __eq__(self, other: object) -> bool:
        """Check equality with another probability space.

        Two probability spaces are equal if they have the same sample space,
        sigma-algebra, and probability measure.

        Parameters
        ----------
        other : object
            Another object to compare with.

        Returns
        -------
        is_equal : bool
            `True` if the other object is a `MeasureSpace` with identical
            components, `False` otherwise.
        """
        if not isinstance(other, MeasureSpace):
            return False
        return (
            self.sample_space == other.sample_space
            and self.sig_alg == other.sig_alg
            and self.prob_measure == other.prob_measure
        )

    # --------------------- representation --------------------- #

    def __repr__(self) -> str:
        """Return a concise string representation of the probability space.

        Returns
        -------
        repr_str : str
            A string representation showing the probability space's component names.
        """
        if (
            self.sample_space is None
            or self.sig_alg is None
            or self.prob_measure is None
        ):
            return "MeasureSpace(empty)"
        return (
            f"MeasureSpace("
            f"sample_space={self.sample_space.name}, "
            f"sig_alg={self.sig_alg.name}, "
            f"prob_measure={self.prob_measure.name})"
        )

    def __str__(self) -> str:
        """Return a detailed string representation of the probability space.

        Returns
        -------
        repr_str : str
            A formatted string showing the probability space header and detailed
            representations of its components.
        """
        if (
            self.sample_space is None
            or self.sig_alg is None
            or self.prob_measure is None
        ):
            return "MeasureSpace(empty)"
        header = (
            f"Probability space ("
            f"{self.sample_space.name}, "
            f"{self.sig_alg.name}, "
            f"{self.prob_measure.name})"
        )
        separator = "=" * len(header)
        return (
            header
            + "\n"
            + separator
            + "\n\n* "
            + repr(self.sample_space)
            + "\n\n* "
            + repr(self.sig_alg)
            + "\n\n* "
            + repr(self.prob_measure)
        )

    # --------------------- validation methods --------------------- #

    @staticmethod
    def _validate_parameters(
        sample_space: SampleSpace | None,
        sig_alg: SigmaAlgebra | None,
        prob_measure: ProbabilityMeasure | None,
    ) -> None:
        """Validate probability space construction parameters.

        Parameters
        ----------
        sample_space : SampleSpace | None
            The sample space to validate.
        sig_alg : SigmaAlgebra | None
            The sigma-algebra to validate.
        prob_measure : ProbabilityMeasure | None
            The probability measure to validate.

        Raises
        ------
        TypeError
            If `sample_space` is not a `SampleSpace` instance (when provided), `sig_algebra` is not a `SigmaAlgebra` instance (when provided), or `prob_measure` is not a `ProbabilityMeasure` instance (when provided).
        ValueError
            If `sig_alg` or `prob_measure` have sample spaces that do
            not match the provided `sample_space`.
        """
        from ..measures import ProbabilityMeasure
        from ..sigma_algebras import SigmaAlgebra
        from .sample_space import SampleSpace

        if sample_space is not None and not isinstance(sample_space, SampleSpace):
            raise TypeError("sample_space must be a SampleSpace instance.")
        if sig_alg is not None and not isinstance(sig_alg, SigmaAlgebra):
            raise TypeError("sig_alg must be a SigmaAlgebra instance.")
        if prob_measure is not None and not isinstance(
            prob_measure, ProbabilityMeasure
        ):
            raise TypeError("prob_measure must be a ProbabilityMeasure instance.")

        if sig_alg is not None and prob_measure is not None:
            if prob_measure.sig_alg != sig_alg:
                raise ValueError(
                    "If both sig_alg and prob_measure are given, the probability measure must be defined on the given sigma-algebra."
                )

        if sample_space is not None:
            if sig_alg is not None and sig_alg.sample_space != sample_space:
                raise ValueError(
                    "If sig_alg is given, its sample space must match the given sample_space."
                )
            if prob_measure is not None and prob_measure.sample_space != sample_space:
                raise ValueError(
                    "If prob_measure is given, its sample space must match the given sample_space."
                )
