"""A class representing a probability space."""

from __future__ import annotations

from typing import TYPE_CHECKING, Literal

from .measure_space import MeasureSpace

if TYPE_CHECKING:
    from collections.abc import Hashable

    from ...typing.index_like import IndexLike
    from ...typing.measure_domain import MeasureDomain
    from ..functions.random_vector import RandomVector
    from ..measures.probability_measure import ProbabilityMeasure
    from ..sigma_algebras.sigma_algebra import SigmaAlgebra
    from .domain import Domain
    from .set import Set


class ProbabilitySpace(MeasureSpace):
    r"""A class representing a probability space.

    See the Notes section below for the mathematical details.

    Parameters
    ----------
    domain : Domain | IndexLike | None, default=None
        The sample space of the probability space.
    sig_alg : SigmaAlgebra | None, default=None
        The sigma-algebra of the probability space.
    measure : ProbabilityMeasure | None, default=None
        The probability measure of the probability space.

    Examples
    --------
    >>> from sigalg.core import ProbabilityMeasure, ProbabilitySpace, SampleSpace, SigmaAlgebra

    Build a `ProbabilitySpace` object with only a sample space. The power-set sigma-algebra and uniform probability measure will be generated by default.

    >>> Omega = SampleSpace.from_sequence(size=3)
    >>> prob_space = ProbabilitySpace(domain=Omega)
    >>> print(prob_space)  # doctest: +NORMALIZE_WHITESPACE
    Probability space (Omega, R, U)
    ===============================
    <BLANKLINE>
    * Sample space 'Omega':
     omega
         0
         1
         2
    <BLANKLINE>
    * Sigma algebra 'R':
           R
    omega
    0      0
    1      1
    2      2
    <BLANKLINE>
    * Probability measure 'U':
                  U
    omega
    0      0.333333
    1      0.333333
    2      0.333333

    Create a probability space with a custom sigma-algebra and probability measure.

    >>> F = SigmaAlgebra(
    ...     domain=Omega,
    ...     mapping={
    ...         0: 0,
    ...         1: 1,
    ...         2: 1,
    ...     },
    ... )
    >>> P = ProbabilityMeasure(
    ...     domain=F,
    ...     mapping={
    ...         0: 0.1,
    ...         1: 0.9,
    ...     },
    ... )
    >>> prob_space = ProbabilitySpace(domain=Omega, sig_alg=F, measure=P)
    >>> print(prob_space)  # doctest: +NORMALIZE_WHITESPACE
    Probability space (Omega, F, P)
    ===============================
    <BLANKLINE>
    * Sample space 'Omega':
     omega
         0
         1
         2
    <BLANKLINE>
    * Sigma algebra 'F':
           F
    omega
    0      0
    1      1
    2      1
    <BLANKLINE>
    * Probability measure 'P':
            P
    F
    0     0.1
    1     0.9

    The same probability space as the latter one may be created with only the measure as an explicit parameter. The sigma-algebra of the probability space is automatically extracted from the measure, and the domain is automatically extracted from the sigma-algebra. Thus, the minimal amount of information needed to construct a `ProbabilitySpace` object is just the measure.

    >>> prob_space = ProbabilitySpace(measure=P)
    >>> print(prob_space)  # doctest: +NORMALIZE_WHITESPACE
    Probability space (Omega, F, P)
    ===============================
    <BLANKLINE>
    * Sample space 'Omega':
    omega
        0
        1
        2
    <BLANKLINE>
    * Sigma algebra 'F':
        F
    omega
    0      0
    1      1
    2      1
    <BLANKLINE>
    * Probability measure 'P':
            P
    F
    0     0.1
    1     0.9

    Notes
    -----
    A *probability space* is a triple $(\Omega, \mathcal{F}, P)$ consisting of a sample space $\Omega$, a $\sigma$-algebra $\mathcal{F}$ on $\Omega$, and a probability measure $P$ defined on $\mathcal{F}$.
    """

    _repr_name = "ProbabilitySpace"
    _str_name = "Probability space"

    # --------------------- constructors --------------------- #

    @classmethod
    def _default_measure(
        cls,
        domain: MeasureDomain | IndexLike | None = None,
    ) -> ProbabilityMeasure:
        from ..measures.probability_measure import ProbabilityMeasure

        return ProbabilityMeasure.uniform(domain=domain)

    @classmethod
    def from_event(
        cls,
        event: Set,
        measure: ProbabilityMeasure | None = None,
    ) -> ProbabilitySpace:
        r"""Create a conditional probability space from an event.

        This method is an alias for `MeasureSpace.from_set` with the `normalize` parameter set to `True`. See the documentation of that method for more details.

        Parameters
        ----------
        event : MeasurableSet
            The event on which to create the conditional probability space.
        measure : ProbabilityMeasure | None, default=None
            The probability measure to use for the conditional probability space. If `None`, the probability measure carried by `event` will be used.

        Returns
        -------
        prob_space : ProbabilitySpace
            A new probability space representing the conditional probability space on the event.

        Examples
        --------
        >>> from sigalg.core import ProbabilityMeasure, ProbabilitySpace, SampleSpace, SigmaAlgebra

        Construct a probability space.

        >>> Omega = SampleSpace.from_sequence(size=6)
        >>> F = SigmaAlgebra(
        ...     domain=Omega,
        ...     mapping={
        ...         0: 0,
        ...         1: 1,
        ...         2: 1,
        ...         3: 2,
        ...         4: 2,
        ...         5: 0,
        ...     },
        ... )
        >>> P = ProbabilityMeasure(
        ...     domain=F,
        ...     mapping={
        ...         0: 0.13,
        ...         1: 0.55,
        ...         2: 0.32,
        ...     },
        ... )
        >>> prob_space = ProbabilitySpace(Omega, F, P)

        Extract an event from the probability space and form the conditional probability space.

        >>> A = prob_space.get_set([1, 2, 3, 4])
        >>> conditional_space = ProbabilitySpace.from_event(A, P)
        >>> print(conditional_space)  # doctest: +NORMALIZE_WHITESPACE
        Probability space (A, F|A, P|A)
        ===============================
        <BLANKLINE>
        * Sample space 'A':
         omega
             1
             2
             3
             4
        <BLANKLINE>
        * Sigma algebra 'F|A':
               F|A
        omega
        1        1
        2        1
        3        2
        4        2
        <BLANKLINE>
        * Probability measure 'P|A':
                   P|A
        F
        1     0.632184
        2     0.367816
        """
        return cls.from_set(subset=event, measure=measure, normalize=True)

    # --------------------- function methods --------------------- #

    def to_rv(
        self,
        domain_name: Hashable = "Omega",
        domain_variable_name: Hashable = "omega",
        index_kind: Literal["Index", "Time"] = "Index",
        index_name: Hashable | None = None,
        name: Hashable = "X",
    ) -> RandomVector:
        """Convert the current probability space to a `RandomVector` instance.

        Parameters
        ----------
        domain_name : Hashable, default="Omega"
            Name of the domain of the random vector.
        domain_variable_name : Hashable, default="omega"
            Name of the domain variable.
        index_kind : Literal["Index", "Time"], default="Index"
            Kind of the index.
        index_name : Hashable | None, default=None
            Name of the index.
        name : Hashable, default="X"
            Name of the random vector.

        Returns
        -------
        rv : RandomVector
            A new `RandomVector` object representing the current probability space.

        Examples
        --------
        >>> from sigalg.core import ProbabilityMeasure, ProbabilitySpace, SampleSpace, SigmaAlgebra

        Define a probability space with a 2-dimensional sample space.

        >>> Omega = SampleSpace.cartesian_product([[1, 2], [1, 3]], variable_names=["A", "B"])
        >>> F = SigmaAlgebra(
        ...     domain=Omega,
        ...     mapping={
        ...         (1, 1): 0,
        ...         (1, 3): 1,
        ...         (2, 1): 1,
        ...         (2, 3): 2,
        ...     },
        ... )
        >>> P = ProbabilityMeasure(
        ...     domain=F,
        ...     mapping={
        ...         0: 0.2,
        ...         1: 0.7,
        ...         2: 0.1,
        ...     },
        ... )
        >>> prob_space = ProbabilitySpace(Omega, F, P)

        Convert to a random vector with default domain parameter values.

        >>> X = prob_space.to_rv()
        >>> print(X)  # doctest: +NORMALIZE_WHITESPACE
        Random vector 'X':
        i      A  B
        omega
        0      1  1
        1      1  3
        2      2  1
        3      2  3

        Convert to a random vector with custom domain parameters values.

        >>> Y = prob_space.to_rv(domain_name="S", domain_variable_name="s", name="Y")
        >>> print(Y)  # doctest: +NORMALIZE_WHITESPACE
        Random vector 'Y':
        i  A  B
        s
        0  1  1
        1  1  3
        2  2  1
        3  2  3
        """
        from ..functions.random_vector import RandomVector
        from ..indices.index import Index
        from ..indices.time import Time
        from ..measures.probability_measure import ProbabilityMeasure
        from ..sigma_algebras.sigma_algebra import SigmaAlgebra

        index_class = Index if index_kind == "Index" else Time
        rv_data = self.domain.data.to_frame().squeeze(axis=1).reset_index(drop=True)
        rv_data.index.name = domain_variable_name
        rv_data.columns.name = index_class._variable_names_prefix

        if self.sig_alg.is_power_set:
            sig_alg = SigmaAlgebra.power_set(
                rv_data.index,
                domain_kind="SampleSpace",
                domain_name=domain_name,
            )
            measure_data = self.measure.data.copy()
            measure_data.index = rv_data.index

        else:
            sig_alg_data = self.sig_alg.data.reset_index(drop=True)
            sig_alg_data.index = rv_data.index
            sig_alg = SigmaAlgebra._from_validated(
                data=sig_alg_data,
                variable_names=self.sig_alg.variable_names,
                domain_kind="SampleSpace",
                domain_name=domain_name,
                index_kind=self.sig_alg.index_kind,
                index_name=self.sig_alg.index_name,
                name=self.sig_alg.name,
            )
            measure_data = self.measure.data

        measure = ProbabilityMeasure._from_validated(
            data=measure_data,
            kind="probability",
            sig_alg=sig_alg,
            name=self.measure.name,
        )

        return RandomVector._from_validated(
            data=rv_data,
            sig_alg=sig_alg,
            measure=measure,
            index_kind=index_kind,
            index_name=index_name,
            name=name,
        )

    # --------------------- validation methods --------------------- #

    @staticmethod
    def _validate_parameters(
        domain: Domain | None,
        sig_alg: SigmaAlgebra | None,
        measure: ProbabilityMeasure | None,
    ) -> None:
        """Validate probability space construction parameters.

        Parameters
        ----------
        domain : Domain | None
            The sample space to validate.
        sig_alg : SigmaAlgebra | None
            The sigma-algebra to validate.
        measure : ProbabilityMeasure | None
            The probability measure to validate.
        """
        from ..measures.probability_measure import ProbabilityMeasure
        from ..sigma_algebras import SigmaAlgebra
        from .domain import Domain

        if domain is not None and not isinstance(domain, Domain):
            raise TypeError("domain must be a Domain instance.")
        if sig_alg is not None and not isinstance(sig_alg, SigmaAlgebra):
            raise TypeError("sig_alg must be a SigmaAlgebra instance.")
        if measure is not None and not isinstance(measure, ProbabilityMeasure):
            raise TypeError("measure must be a ProbabilityMeasure instance.")

        if sig_alg is not None and measure is not None:
            if not (measure.sig_alg <= sig_alg) and not (measure.sig_alg > sig_alg):
                raise ValueError(
                    "If both sig_alg and measure are given, the measure must be defined on either a super- or sub-sigma-algebra of the given sigma-algebra."
                )

        if domain is not None:
            if sig_alg is not None and sig_alg.domain != domain:
                raise ValueError(
                    "If sig_alg is given, its domain must match the given domain."
                )
            if measure is not None and measure.sig_alg.domain != domain:
                raise ValueError(
                    "If measure is given, its domain must match the given domain."
                )
