"""A class representing a probability space."""

from __future__ import annotations

from typing import TYPE_CHECKING

from .measure_space import MeasureSpace

if TYPE_CHECKING:
    from ...typing.index_like import IndexLike
    from ...typing.measure_domain import MeasureDomain
    from ..measures.probability_measure import ProbabilityMeasure
    from ..sigma_algebras.sigma_algebra import SigmaAlgebra
    from .domain import Domain
    from .measurable_set import MeasurableSet


class ProbabilitySpace(MeasureSpace):
    r"""A class representing a probability space.

    See the Notes section below for the mathematical details.

    If all three of `domain`, `sig_alg`, and `measure` are provided, the `domain` of the provided `sig_alg` must match the provided `domain`, and the `sig_alg` of the provided `measure` must match the provided `sig_alg`. Otherwise, if only some of the parameters are provided, the missing components will be automatically created to be compatible with the provided ones as follows:

    * If `domain` is not provided but `sig_alg` or `measure` is given, then `domain` will be taken from the provided `sig_alg` or `measure`.
    * If `sig_alg` is not provided but `domain` or `measure` is given, then `sig_alg` will be set to the power-set sigma-algebra on the provided `domain` (if given) or the sigma-algebra of the provided `measure` (if given).
    * If `measure` is not provided but `domain` or `sig_alg` is given, then `measure` will be set to the uniform probability measure on the provided `sig_alg` (if given) or the power-set sigma-algebra on the provided `domain` (if given).

    If none of the parameters are provided, all components will be initialized to `None` and can be set later.

    Parameters
    ----------
    domain : Domain | IndexLike | None, default=None
        The sample space of the probability space.
    sig_alg : SigmaAlgebra | None, default=None
        The sigma-algebra of the probability space.
    measure : ProbabilityMeasure | None, default=None
        The probability measure of the probability space.

    Examples
    --------
    Build a `ProbabilitySpace` object with only a sample space. The power-set sigma-algebra and uniform probability measure will be generated by default.

    >>> from sigalg.core import ProbabilityMeasure, ProbabilitySpace, SampleSpace, SigmaAlgebra
    >>> Omega = SampleSpace.from_sequence(size=3)
    >>> prob_space = ProbabilitySpace(domain=Omega)
    >>> print(prob_space)  # doctest: +NORMALIZE_WHITESPACE
    Probability space (Omega, R, U)
    ===============================
    <BLANKLINE>
    * Sample space 'Omega':
     sample
          0
          1
          2
    <BLANKLINE>
    * Sigma algebra 'R':
             sample
    sample
    0             0
    1             1
    2             2
    <BLANKLINE>
    * Probability measure 'U':
            probability
    sample
    0          0.333333
    1          0.333333
    2          0.333333

    Create a probability space with a custom sigma-algebra and probability measure.

    >>> F = SigmaAlgebra(
    ...     domain=Omega,
    ...     mapping={
    ...         0: 0,
    ...         1: 1,
    ...         2: 1,
    ...     },
    ... )
    >>> P = ProbabilityMeasure(
    ...     domain=F,
    ...     mapping={
    ...         0: 0.1,
    ...         1: 0.9,
    ...     },
    ... )
    >>> prob_space = ProbabilitySpace(domain=Omega, sig_alg=F, measure=P)
    >>> print(prob_space)  # doctest: +NORMALIZE_WHITESPACE
    Probability space (Omega, F, P)
    ===============================
    <BLANKLINE>
    * Sample space 'Omega':
     sample
          0
          1
          2
    <BLANKLINE>
    * Sigma algebra 'F':
            atom_ID
    sample
    0             0
    1             1
    2             1
    <BLANKLINE>
    * Probability measure 'P':
            probability
    atom_ID
    0               0.1
    1               0.9

    Notes
    -----
    A *probability space* is a triple $(\Omega, \mathcal{F}, P)$ consisting of a sample space $\Omega$, a $\sigma$-algebra $\mathcal{F}$ on $\Omega$, and a probability measure $P$ defined on $\mathcal{F}$.
    """

    _repr_name = "ProbabilitySpace"
    _str_name = "Probability space"

    # --------------------- constructors --------------------- #

    @classmethod
    def _default_measure(
        cls,
        domain: MeasureDomain | IndexLike | None = None,
    ) -> ProbabilityMeasure:
        from ..measures.probability_measure import ProbabilityMeasure

        return ProbabilityMeasure.uniform(domain=domain)

    @classmethod
    def from_event(
        cls,
        event: MeasurableSet,
        measure: ProbabilityMeasure | None = None,
    ) -> ProbabilitySpace:
        r"""Create a conditional probability space from an event.

        This method is an alias for `MeasureSpace.from_set` with the `normalize` parameter set to `True`. See the documentation of that method for more details.

        Parameters
        ----------
        event : MeasurableSet
            The event on which to create the conditional probability space.
        measure : ProbabilityMeasure | None, default=None
            The probability measure to use for the conditional probability space. If `None`, the probability measure carried by `event` will be used.

        Returns
        -------
        prob_space : ProbabilitySpace
            A new probability space representing the conditional probability space on the event.

        Examples
        --------
        Construct a probability space.

        >>> from sigalg.core import ProbabilityMeasure, ProbabilitySpace, SampleSpace, SigmaAlgebra
        >>> Omega = SampleSpace.from_sequence(size=6)
        >>> F = SigmaAlgebra(
        ...     domain=Omega,
        ...     mapping={
        ...         0: 0,
        ...         1: 1,
        ...         2: 1,
        ...         3: 2,
        ...         4: 2,
        ...         5: 0,
        ...     },
        ... )
        >>> P = ProbabilityMeasure(
        ...     domain=F,
        ...     mapping={
        ...         0: 0.13,
        ...         1: 0.55,
        ...         2: 0.32,
        ...     },
        ... )
        >>> prob_space = ProbabilitySpace(Omega, F, P)

        Extract an event from the probability space and form the conditional probability space.

        >>> A = prob_space.get_set([1, 2, 3, 4])
        >>> conditional_space = ProbabilitySpace.from_event(A, P)
        >>> print(conditional_space)  # doctest: +NORMALIZE_WHITESPACE
        Probability space (A, F_A, P_A)
        ===============================
        <BLANKLINE>
        * Sample space 'A':
         sample
              1
              2
              3
              4
        <BLANKLINE>
        * Sigma algebra 'F_A':
                atom_ID
        sample
        1             1
        2             1
        3             2
        4             2
        <BLANKLINE>
        * Probability measure 'P_A':
                 probability
        atom_ID
        1           0.632184
        2           0.367816
        """
        return cls.from_set(measurable_set=event, measure=measure, normalize=True)

    # --------------------- validation methods --------------------- #

    @staticmethod
    def _validate_parameters(
        domain: Domain | None,
        sig_alg: SigmaAlgebra | None,
        measure: ProbabilityMeasure | None,
    ) -> None:
        """Validate probability space construction parameters.

        Parameters
        ----------
        domain : Domain | None
            The sample space to validate.
        sig_alg : SigmaAlgebra | None
            The sigma-algebra to validate.
        measure : ProbabilityMeasure | None
            The probability measure to validate.

        Raises
        ------
        TypeError
            If `domain` is not a `SampleSpace` instance (when provided), `sig_alg` is not a `SigmaAlgebra` instance (when provided), or `measure` is not a `ProbabilityMeasure` instance (when provided).
        ValueError
            If `sig_alg` or `measure` have domains that do
            not match the provided `domain`.
        """
        from ..measures.probability_measure import ProbabilityMeasure
        from ..sigma_algebras import SigmaAlgebra
        from .domain import Domain

        if domain is not None and not isinstance(domain, Domain):
            raise TypeError("domain must be a Domain instance.")
        if sig_alg is not None and not isinstance(sig_alg, SigmaAlgebra):
            raise TypeError("sig_alg must be a SigmaAlgebra instance.")
        if measure is not None and not isinstance(measure, ProbabilityMeasure):
            raise TypeError("measure must be a ProbabilityMeasure instance.")

        if sig_alg is not None and measure is not None:
            if not (measure.sig_alg <= sig_alg) and not (measure.sig_alg > sig_alg):
                raise ValueError(
                    "If both sig_alg and measure are given, the measure must be defined on either a super- or sub-sigma-algebra of the given sigma-algebra."
                )

        if domain is not None:
            if sig_alg is not None and sig_alg.domain != domain:
                raise ValueError(
                    "If sig_alg is given, its domain must match the given domain."
                )
            if measure is not None and measure.sig_alg.domain != domain:
                raise ValueError(
                    "If measure is given, its domain must match the given domain."
                )
