import numpy as np
import pytest

from sigalg.core import Time
from sigalg.finance import TrinomialPricingModel


class TestPriceProcess:
    def test_price_process(self):
        """Test that the price process generated by the trinomial pricing model is correct."""
        S_0 = 4
        u = 1.2
        m = 1.1
        d = 0.9
        p_u = 0.6
        p_d = 0.1
        r = 0.01
        T = 2

        time = Time.discrete(length=T)
        S = TrinomialPricingModel(
            initial_price=S_0,
            up_factor=u,
            middle_factor=m,
            down_factor=d,
            up_prob=p_u,
            down_prob=p_d,
            risk_free_rate=r,
            time=time,
        ).from_enumeration()

        expected_prices = S_0 * np.array(
            [
                [1, u, u**2],  # uu
                [1, u, u * m],  # um
                [1, u, u * d],  # ud
                [1, m, m * u],  # mu
                [1, m, m**2],  # mm
                [1, m, m * d],  # md
                [1, d, d * u],  # du
                [1, d, d * m],  # dm
                [1, d, d**2],  # dd
            ]
        )

        assert np.allclose(S.data.values, expected_prices)


class TestProbabilityMeasures:
    def test_real_world_measure(self):
        """Test that the real-world measure of the trinomial pricing model is correct."""
        S_0 = 4
        u = 1.2
        m = 1.1
        d = 0.9
        p_u = 0.6
        p_d = 0.1
        r = 0.01
        T = 2
        time = Time.discrete(length=T)
        S = TrinomialPricingModel(
            initial_price=S_0,
            up_factor=u,
            middle_factor=m,
            down_factor=d,
            up_prob=p_u,
            down_prob=p_d,
            risk_free_rate=r,
            time=time,
        ).from_enumeration()

        p_u = S.up_prob
        p_d = S.down_prob
        p_m = 1 - p_u - p_d

        expected_probabilities = np.array(
            [
                p_u**2,
                p_u * p_m,
                p_u * p_d,
                p_m * p_u,
                p_m**2,
                p_m * p_d,
                p_d * p_u,
                p_d * p_m,
                p_d**2,
            ]
        )

        assert np.allclose(S.prob_measure.data.values, expected_probabilities)

    def test_risk_neutral_probs_with_R_less_than_m(self):
        """Test that the risk-neutral probabilities are correct when R is less than m."""
        S_0 = 4
        u = 1.2
        m = 1.1
        d = 0.9
        p_u = 0.6
        p_d = 0.1
        r = 0.01
        T = 2
        time = Time.discrete(length=T)
        S = TrinomialPricingModel(
            initial_price=S_0,
            up_factor=u,
            middle_factor=m,
            down_factor=d,
            up_prob=p_u,
            down_prob=p_d,
            risk_free_rate=r,
            time=time,
        ).from_enumeration()

        for theta in np.arange(start=0.01, stop=1, step=0.01):
            q_u, q_m, q_d = S.risk_neutral_probs(theta=theta)

            assert 0 < q_u and q_u < 1
            assert 0 < q_m and q_m < 1
            assert 0 < q_d and q_d < 1
            assert np.allclose(q_u + q_m + q_d, 1)

    def test_risk_neutral_probs_with_R_greater_than_m(self):
        """Test that the risk-neutral probabilities are correct when R is greater than m."""
        S_0 = 4
        u = 1.2
        m = 1.1
        d = 0.9
        p_u = 0.6
        p_d = 0.1
        r = 0.15
        T = 2
        time = Time.discrete(length=T)
        S = TrinomialPricingModel(
            initial_price=S_0,
            up_factor=u,
            middle_factor=m,
            down_factor=d,
            up_prob=p_u,
            down_prob=p_d,
            risk_free_rate=r,
            time=time,
        ).from_enumeration()

        for theta in np.arange(start=0.01, stop=1, step=0.01):
            q_u, q_m, q_d = S.risk_neutral_probs(theta=theta)

            assert 0 < q_u and q_u < 1
            assert 0 < q_m and q_m < 1
            assert 0 < q_d and q_d < 1
            assert np.allclose(q_u + q_m + q_d, 1)

    def test_arbitrage_raises(self):
        """Test that an error is raised when there is arbitrage in the model (i.e., when R is not in the interval [d, u])."""
        S_0 = 4
        u = 1.2
        m = 1.1
        d = 0.9
        p_u = 0.6
        p_d = 0.1
        r = 0.3
        T = 2
        time = Time.discrete(length=T)

        S = TrinomialPricingModel(
            initial_price=S_0,
            up_factor=u,
            middle_factor=m,
            down_factor=d,
            up_prob=p_u,
            down_prob=p_d,
            risk_free_rate=r,
            time=time,
        )

        with pytest.raises(ValueError, match="arbitrage"):
            S.risk_neutral_probs(theta=0.5)

    def test_equivalent_martingale_measures(self):
        S_0 = 4
        u = 1.2
        m = 1.1
        d = 0.9
        p_u = 0.6
        p_d = 0.1
        r = 0.01
        T = 3

        time = Time.discrete(length=T)
        S = TrinomialPricingModel(
            initial_price=S_0,
            up_factor=u,
            middle_factor=m,
            down_factor=d,
            up_prob=p_u,
            down_prob=p_d,
            risk_free_rate=r,
            time=time,
        ).from_enumeration()

        for theta in np.arange(start=0.01, stop=1, step=0.01):
            P_theta = S.emms(theta=theta)
            q_u, q_m, q_d = S.risk_neutral_probs(theta=theta)
            expected_probs = np.array(
                [
                    q_u**3,
                    q_u**2 * q_m,
                    q_u**2 * q_d,
                    q_u * q_m * q_u,
                    q_u * q_m**2,
                    q_u * q_m * q_d,
                    q_u * q_d * q_u,
                    q_u * q_d * q_m,
                    q_u * q_d**2,
                    q_m * q_u * q_u,
                    q_m * q_u * q_m,
                    q_m * q_u * q_d,
                    q_m**2 * q_u,
                    q_m**3,
                    q_m**2 * q_d,
                    q_m * q_d * q_u,
                    q_m * q_d * q_m,
                    q_m * q_d**2,
                    q_d * q_u * q_u,
                    q_d * q_u * q_m,
                    q_d * q_u * q_d,
                    q_d * q_m * q_u,
                    q_d * q_m * q_m,
                    q_d * q_m * q_d,
                    q_d**2 * q_u,
                    q_d**2 * q_m,
                    q_d**3,
                ]
            )

            assert np.allclose(P_theta.data.values, expected_probs)
