# from ..spaces import SampleSpace, SamplePointsIndex, Event
# from typing import List
# import pandas as pd


# class SigmaAlgebra:

#     def __init__(self, sample_space: SampleSpace, atom_ids: List | str) -> None:

#         if not isinstance(sample_space, SampleSpace):
#             raise ValueError("sample_space must be an instance of SampleSpace.")
#         if isinstance(atom_ids, str):
#             if atom_ids == "power_set":
#                 atom_ids = list(range(len(sample_space)))
#             elif atom_ids == "trivial":
#                 atom_ids = [0] * len(sample_space)
#             else:
#                 raise ValueError(f"Unknown atom_ids string: {atom_ids}")
#         if not isinstance(atom_ids, list):
#             raise ValueError("atom_ids must be a list or a string.")
#         if len(atom_ids) != len(sample_space):
#             raise ValueError("Length of atom_ids must match length of sample_space.")

#         self._sample_space = sample_space
#         self._atom_ids = pd.Series(data=atom_ids, index=sample_space._df.index)
#         self._atoms_by_indices: List[SamplePointsIndex] = [
#             SamplePointsIndex(data=sample_space._df.index[self._atom_ids == a])
#             for a in self._atom_ids.unique()
#         ]
#         self._filtration = None

#     def __len__(self) -> int:
#         return len(self._atom_ids.unique())

#     @property
#     def atoms_with_ids(self):
#         grouped = self._sample_space._df.groupby(self._atom_ids)
#         group_items = {name: Event(sample_space=group) for name, group in grouped}
#         return group_items

#     @property
#     def atoms(self) -> List[Event]:
#         """List of atoms as Event objects."""
#         return list(self.atoms_with_ids.values())

#     def atom_id_of(self, sample_point_index) -> Event:
#         return self._atom_ids.loc[sample_point_index]

#     # def is_subalgebra_of(self, other: "SigmaAlgebra") -> bool:
#     #     """
#     #     Check if this sigma-algebra is a sub-sigma-algebra of another.

#     #     A sigma-algebra F (`self`) will be a sub-sigma-algebra of another algebra G (`other`) if (and only if) every atom of G is a subset of an atom of F. We check this by first grouping the sample space by the atoms of G, and then checking that within each of these atoms, the atom labels from F are all the same.

#     #     Parameters
#     #     ----------
#     #     other : SigmaAlgebra
#     #         The sigma-algebra to compare against.

#     #     Raises
#     #     ------
#     #     ValueError
#     #         If the two sigma-algebras do not share the same SampleSpace instance.
#     #     """
#     #     if self.sample_space is not other.sample_space:
#     #         raise ValueError("Sigma-algebras must share the same SampleSpace instance.")

#     #     pairs = pd.DataFrame({"self": self.atom_ids, "other": other.atom_ids})

#     #     return pairs.groupby("other")["self"].nunique().le(1).all()

#     # def is_superalgebra_of(self, other: "SigmaAlgebra") -> bool:
#     #     """
#     #     Check if this sigma-algebra is a super-sigma-algebra of another.

#     #     A sigma-algebra F (`self`) will be a super-sigma-algebra of another algebra G (`other`) if (and only if) every atom of F is a subset of an atom of G. We check this by first grouping the sample space by the atoms of F, and then checking that within each of these atoms, the atom labels from G are all the same.

#     #     Parameters
#     #     ----------
#     #     other : SigmaAlgebra
#     #         The sigma-algebra to compare against.

#     #     Raises
#     #     ------
#     #     ValueError
#     #         If the two sigma-algebras do not share the same SampleSpace instance.
#     #     """
#     #     if self.sample_space is not other.sample_space:
#     #         raise ValueError("Sigma-algebras must share the same SampleSpace instance.")

#     #     pairs = pd.DataFrame({"self": self.atom_ids, "other": other.atom_ids})

#     #     return pairs.groupby("self")["other"].nunique().le(1).all()

#     # @classmethod
#     # def generated_by(cls, random_variables):
#     #     """
#     #     Create the sigma-algebra generated by a list of random variables.

#     #     The generated sigma-algebra is the coarsest sigma-algebra that makes
#     #     all the given random variables measurable. Two sample points are in
#     #     the same atom if and only if they have the same values for all the
#     #     random variables.

#     #     Parameters
#     #     ----------
#     #     random_variables : List[RandomVariable]
#     #         A list of random variables that generate the sigma-algebra.

#     #     Returns
#     #     -------
#     #     SigmaAlgebra
#     #         The sigma-algebra generated by the random variables.

#     #     Raises
#     #     ------
#     #     ValueError
#     #         If the list is empty or if random variables don't share the same
#     #         sample space.

#     #     Examples
#     #     --------
#     #     >>> import sigalg as sa
#     #     >>> import pandas as pd
#     #     >>> def X_function(row: pd.Series) -> float:
#     #     ...     numerical_row = row.apply(lambda x: 0 if x == "T" else 1)
#     #     ...     return numerical_row.sum()
#     #     >>> def Y_function(row: pd.Series) -> float:
#     #     ...     numerical_row = row.apply(lambda x: 0 if x == "T" else 1)
#     #     ...     return numerical_row[1]
#     #     >>> state_space = ["T", "H"]
#     #     >>> time = sa.DiscreteTime.from_list([0, 1, 2])
#     #     >>> sample_space = sa.SampleSpace.create_sequence_space(state_space, time)
#     #     >>> X = sa.RandomVariable(sample_space=sample_space, rv_function=X_function)
#     #     >>> Y = sa.RandomVariable(sample_space=sample_space, rv_function=Y_function)
#     #     >>> print(
#     #     ...     pd.concat([sample_space, X.rv_values.rename("X"),
#     #     ...     Y.rv_values.rename("Y")], axis=1)
#     #     ... )
#     #               0  1  2  X  Y
#     #     sequence
#     #     omega1    T  T  T  0  0
#     #     omega2    T  T  H  1  0
#     #     omega3    T  H  T  1  1
#     #     omega4    T  H  H  2  1
#     #     omega5    H  T  T  1  0
#     #     omega6    H  T  H  2  0
#     #     omega7    H  H  T  2  1
#     #     omega8    H  H  H  3  1
#     #     >>> F = sa.SigmaAlgebra.generated_by([X, Y])
#     #     >>> print(F)
#     #     SigmaAlgebra instance on sample space with 8 points
#     #     number of atoms: 6
#     #      atom 0: ['omega1']
#     #      atom 1: ['omega2', 'omega5']
#     #      atom 2: ['omega3']
#     #      atom 3: ['omega4', 'omega7']
#     #      atom 4: ['omega6']
#     #     ...
#     #     """
#     #     if not isinstance(random_variables, list) or len(random_variables) == 0:
#     #         raise ValueError(
#     #             "random_variables must be a non-empty list of RandomVariable instances"
#     #         )

#     #     # Check all RVs share the same sample space
#     #     sample_space = random_variables[0].sample_space
#     #     for rv in random_variables[1:]:
#     #         if rv.sample_space is not sample_space:
#     #             raise ValueError(
#     #                 "All random variables must be defined on the same sample space"
#     #             )

#     #     # Create a DataFrame with all RV values
#     #     rv_values_df = pd.DataFrame(
#     #         {f"rv_{i}": rv.rv_values for i, rv in enumerate(random_variables)}
#     #     )

#     #     # Group by unique combinations of RV values
#     #     # Each unique combination forms an atom
#     #     atom_labels = rv_values_df.groupby(
#     #         list(rv_values_df.columns), sort=False
#     #     ).ngroup()
#     #     atom_labels.name = "atom_id"

#     #     return cls(sample_space, atom_labels)

#     # def __repr__(self) -> str:
#     #     cls = self.__class__.__name__
#     #     return f"{cls}(n_atoms={len(self.atoms)})"

#     # def __eq__(self, other: "SigmaAlgebra") -> bool:
#     #     """
#     #     Check if two sigma-algebras are equal (same atoms).

#     #     Parameters
#     #     ----------
#     #     other : SigmaAlgebra
#     #         The sigma-algebra to compare against.

#     #     Returns
#     #     -------
#     #     bool
#     #         True if the sigma-algebras are equal, False otherwise.
#     #     """
#     #     if not isinstance(other, SigmaAlgebra):
#     #         return False
#     #     if self.sample_space is not other.sample_space:
#     #         return False
#     #     return self.atom_ids.equals(other.atom_ids)
