"""A class representing a probability space."""

from __future__ import annotations

from collections.abc import Hashable
from numbers import Real
from typing import TYPE_CHECKING

import numpy as np

from ..probability_measures.probability_measure import ProbabilityMeasureMethods
from ..sigma_algebras.sigma_algebra import SigmaAlgebraMethods

if TYPE_CHECKING:
    from ..probability_measures import ProbabilityMeasure
    from ..sigma_algebras import SigmaAlgebra
    from .event import Event
    from .sample_space import SampleSpace


class ProbabilitySpace(SigmaAlgebraMethods, ProbabilityMeasureMethods):
    r"""A class representing a probability space.

    See the Notes section below for the mathematical details.

    Parameters
    ----------
    sample_space : SampleSpace | None, default=None
        The sample space containing all possible outcomes. If `None`, a sample space will be automatically generated by other methods (e.g., the `from_dict` method).
    sig_alg : SigmaAlgebra | None, default=None
        Sigma-algebra defining measurable events. If `None`, a power set
        sigma-algebra is created.
    prob_measure : ProbabilityMeasure | None, default=None
        Probability measure assigning probabilities to outcomes. If `None`,
        a uniform probability measure is created.

    Raises
    ------
    TypeError
        If `sample_space` is not a `SampleSpace` instance, `sig_alg` is not a `SigmaAlgebra` instance (when provided), or `prob_measure` is not a `ProbabilityMeasure` instance (when provided).
    ValueError
        If `sig_alg` or `prob_measure` have sample spaces that do not match the provided `sample_space`.

    Examples
    --------
    >>> from sigalg.core import ProbabilityMeasure, ProbabilitySpace, SampleSpace, SigmaAlgebra
    >>> Omega = SampleSpace().from_sequence(size=3)
    >>> # Create with default uniform probability measure and power-set sigma-algebra
    >>> prob_space = ProbabilitySpace(sample_space=Omega)
    >>> print(prob_space) # doctest: +NORMALIZE_WHITESPACE
    Probability space (Omega, power_set, P)
    =======================================
    <BLANKLINE>
    * Sample space 'Omega':
    [0, 1, 2]
    <BLANKLINE>
    * Sigma algebra 'power_set':
            atom ID
    sample
    0             0
    1             1
    2             2
    <BLANKLINE>
    * Probability measure 'P':
            probability
    sample
    0          0.333333
    1          0.333333
    2          0.333333
    >>> # Create with a custom probability measure and sigma-algebra
    >>> P = ProbabilityMeasure(sample_space=Omega).from_dict(
    ...     {
    ...             0: 0.5,
    ...             1: 0.3,
    ...             2: 0.2,
    ...     }
    ... )
    >>> F = SigmaAlgebra(sample_space=Omega).from_dict(
    ...     {
    ...             0: 0,
    ...             1: 1,
    ...             2: 1,
    ...     }
    ... )
    >>> prob_space = ProbabilitySpace(sample_space=Omega, sig_alg=F, prob_measure=P)
    >>> print(prob_space) # doctest: +NORMALIZE_WHITESPACE
    Probability space (Omega, F, P)
    ===============================
    <BLANKLINE>
    * Sample space 'Omega':
    [0, 1, 2]
    <BLANKLINE>
    * Sigma algebra 'F':
            atom ID
    sample
    0             0
    1             1
    2             1
    <BLANKLINE>
    * Probability measure 'P':
            probability
    sample
    0               0.5
    1               0.3
    2               0.2

    Notes
    -----
    A *probability space* is a triple $(\Omega, \mathcal{F}, P)$ constiting of a sample space $\Omega$, a $\sigma$-algebra $\mathcal{F}$ on $\Omega$, and a probability measure $P$ defined on $\mathcal{F}$.

    See also the [notebook](https://johnmyers-phd.com/sigalg/dictionary/){target="_blank"} on the docs website.
    """

    # --------------------- constructor --------------------- #

    def __init__(
        self,
        sample_space: SampleSpace | None = None,
        sig_alg: SigmaAlgebra | None = None,
        prob_measure: ProbabilityMeasure | None = None,
    ) -> None:
        from ..probability_measures import ProbabilityMeasure
        from ..sigma_algebras import SigmaAlgebra

        if sample_space is not None:
            self._validate_parameters(sample_space, sig_alg, prob_measure)
            if sig_alg is None:
                sig_alg = SigmaAlgebra.power_set(sample_space)
            if prob_measure is None:
                prob_measure = ProbabilityMeasure.uniform(sig_alg)
        else:
            if sig_alg is not None:
                raise ValueError(
                    "If sample_space is not given, sig_alg must also be None."
                )
            if prob_measure is not None:
                raise ValueError(
                    "If sample_space is not given, prob_measure must also be None."
                )

        self._sample_space = sample_space
        self._sig_alg = sig_alg
        self._prob_measure = prob_measure

    # --------------------- properties --------------------- #

    @property
    def sample_space(self) -> SampleSpace:
        """Get the sample space containing all possible outcomes.

        Returns
        -------
        sample_space : SampleSpace
            The sample space of this probability space.
        """
        return self._sample_space

    @sample_space.setter
    def sample_space(self, sample_space: SampleSpace | None = None) -> None:
        """Set the sample space containing all possible outcomes.

        Parameters
        ----------
        sample_space : SampleSpace | None, default=None
            New sample space or `None`. If not `None`, the existing sigma-algebra and probability measure will be reset to the power-set sigma-algebra and uniform probability measure on the new sample space.
        """
        from ..probability_measures.probability_measure import ProbabilityMeasure
        from ..sigma_algebras.sigma_algebra import SigmaAlgebra
        from .sample_space import SampleSpace

        if sample_space is not None:
            if not isinstance(sample_space, SampleSpace):
                raise TypeError("sample_space must be a SampleSpace instance.")
            self._sig_alg = SigmaAlgebra.power_set(sample_space)
            self._prob_measure = ProbabilityMeasure.uniform(self._sig_alg)
        self._sample_space = sample_space

    @property
    def prob_measure(self) -> ProbabilityMeasure:
        """Get the probability measure assigning probabilities to events.

        Returns
        -------
        prob : ProbabilityMeasure
            The probability measure of this probability space.

        Examples
        --------
        >>> from sigalg.core import ProbabilityMeasure, ProbabilitySpace, SampleSpace, SigmaAlgebra
        >>> Omega = SampleSpace().from_sequence(size=3)
        >>> P = ProbabilityMeasure(sample_space=Omega).from_dict(
        ...     {
        ...             0: 0.5,
        ...             1: 0.3,
        ...             2: 0.2,
        ...     }
        ... )
        >>> F = SigmaAlgebra(sample_space=Omega).from_dict(
        ...     {
        ...             0: 0,
        ...             1: 1,
        ...             2: 1,
        ...     }
        ... )
        >>> prob_space = ProbabilitySpace(sample_space=Omega, sig_alg=F, prob_measure=P)
        >>> print(prob_space.prob_measure) # doctest: +NORMALIZE_WHITESPACE
        Probability measure 'P':
                probability
        sample
        0               0.5
        1               0.3
        2               0.2
        """
        return self._prob_measure

    @prob_measure.setter
    def prob_measure(self, prob_measure: ProbabilityMeasure) -> None:
        """Set the probability measure assigning probabilities to events.

        Parameters
        ----------
        prob_measure : ProbabilityMeasure
            New probability measure. Must have the same sample space as this
            probability space.

        Raises
        ------
        TypeError
            If `prob_measure` is not a `ProbabilityMeasure` instance.
        ValueError
            If `prob_measure`'s sample space does not match this probability
            space's sample space.
        """
        if self.sample_space is None:
            raise ValueError("Cannot set prob_measure without a sample_space.")
        self._validate_parameters(self.sample_space, self.sig_alg, prob_measure)
        self._prob_measure = prob_measure

    @property
    def sig_alg(self) -> SigmaAlgebra:
        """Get the sigma-algebra defining measurable events.

        Returns
        -------
        sig_algebra : SigmaAlgebra
            The sigma-algebra of this probability space.

        Examples
        --------
        >>> from sigalg.core import ProbabilityMeasure, ProbabilitySpace, SampleSpace, SigmaAlgebra
        >>> Omega = SampleSpace().from_sequence(size=3)
        >>> P = ProbabilityMeasure(sample_space=Omega).from_dict(
        ...     {
        ...             0: 0.5,
        ...             1: 0.3,
        ...             2: 0.2,
        ...     }
        ... )
        >>> F = SigmaAlgebra(sample_space=Omega).from_dict(
        ...     {
        ...             0: 0,
        ...             1: 1,
        ...             2: 1,
        ...     }
        ... )
        >>> prob_space = ProbabilitySpace(sample_space=Omega, sig_alg=F, prob_measure=P)
        >>> print(prob_space.sig_alg) # doctest: +NORMALIZE_WHITESPACE
        Sigma algebra 'F':
                atom ID
        sample
        0             0
        1             1
        2             1
        """
        return self._sig_alg

    @sig_alg.setter
    def sig_alg(self, sig_alg: SigmaAlgebra) -> None:
        """Set the sigma-algebra defining measurable events.

        Parameters
        ----------
        sig_alg : SigmaAlgebra
            New sigma-algebra. Must have the same sample space as this
            probability space.

        Raises
        ------
        TypeError
            If `sig_alg` is not a `SigmaAlgebra` instance.
        ValueError
            If `sig_alg`'s sample space does not match this probability
            space's sample space.
        """
        if self.sample_space is None:
            raise ValueError("Cannot set sig_alg without a sample_space.")
        self._validate_parameters(self.sample_space, sig_alg, self.prob_measure)
        self._sig_alg = sig_alg

    # --------------------- factory methods --------------------- #

    def from_dict(
        self,
        probabilities: dict[Hashable, Real],
    ) -> ProbabilitySpace:
        """Create a probability space from a dictionary of probabilities.

        If a `sample_space` was not provided during initialization, it will be created from the keys of the provided dictionary. If it was provided, it must match the keys of the provided dictionary.

        If a `sig_algebra` was not provided during initialization, a power set sigma-algebra will be created on the sample space. If it was provided, its sample space must match the keys of the provided dictionary.

        Parameters
        ----------
        probabilities : dict[Hashable, Real]
            Dictionary mapping sample point indices to their probabilities.
            Probabilities must be non-negative and sum to 1.

        Raises
        ------
        TypeError
            If `probabilities` is not a dictionary.
        ValueError
            If the keys of `probabilities` do not match the sample space (if given).

        Returns
        -------
        probability_space : ProbabilitySpace
            A new probability space with the specified probabilities.

        Examples
        --------
        >>> from sigalg.core import ProbabilitySpace
        >>> prob_space = ProbabilitySpace().from_dict(
        ...     {
        ...             "a": 0.5,
        ...             "b": 0.3,
        ...             "c": 0.2,
        ...     }
        ... )
        >>> print(prob_space) # doctest: +NORMALIZE_WHITESPACE
        Probability space (Omega, power_set, P)
        =======================================
        <BLANKLINE>
        * Sample space 'Omega':
        ['a', 'b', 'c']
        <BLANKLINE>
        * Sigma algebra 'power_set':
                atom ID
        sample
        a             0
        b             1
        c             2
        <BLANKLINE>
        * Probability measure 'P':
                probability
        sample
        a               0.5
        b               0.3
        c               0.2
        """
        from ..probability_measures import ProbabilityMeasure
        from ..sigma_algebras.sigma_algebra import SigmaAlgebra
        from .sample_space import SampleSpace

        if not isinstance(probabilities, dict):
            raise TypeError("probabilities must be a dictionary.")

        if self.sample_space is not None:
            if set(probabilities.keys()) != set(self.sample_space):
                raise ValueError(
                    "If sample_space was given during initialization, its elements must match the keys of the probabilities dictionary."
                )
        else:
            self.sample_space = SampleSpace().from_list(list(probabilities.keys()))

        if self.sig_alg is None:
            self.sig_alg = SigmaAlgebra.power_set(self.sample_space)

        self.prob_measure = ProbabilityMeasure(sig_alg=self.sig_alg).from_dict(
            probabilities=probabilities
        )

        return self

    @classmethod
    def from_event(
        cls,
        event: Event,
        prob_measure: ProbabilityMeasure,
        sig_algebra: SigmaAlgebra | None = None,
    ) -> ProbabilitySpace:
        r"""Create a conditional probability space from an event.

        See the Notes section below for the mathematical details.

        Parameters
        ----------
        event : Event
            The event on which to create the conditional probability space.
        prob_measure : ProbabilityMeasure
            The probability measure to use for the conditional probability space.
        sig_alg : SigmaAlgebra | None, default=None
            Optional sigma-algebra to use for the conditional probability space. If `None`, a power set sigma-algebra will be created on the sample space of the event.

        Raises
        ------
        TypeError
            If `event` is not an `Event` instance, `prob_measure` is not a `ProbabilityMeasure` instance, or `sig_alg` is not a `SigmaAlgebra` instance (when provided).
        ValueError
            If `prob_measure` or `sig_algebra` have sample spaces that do not match the sample space of the event, if `sig_algebra` is given and does not contain the event, or if the probability of the event under the given probability measure is zero.

        Returns
        -------
        prob_space : ProbabilitySpace
            A new probability space representing the conditional probability space on the event.

        Examples
        --------
        >>> from sigalg.core import ProbabilityMeasure, ProbabilitySpace, SampleSpace, SigmaAlgebra
        >>> Omega = SampleSpace().from_sequence(size=4)
        >>> P = ProbabilityMeasure(sample_space=Omega).from_dict(
        ...     {
        ...         0: 0.15,
        ...         1: 0.25,
        ...         2: 0.35,
        ...         3: 0.25,
        ...     }
        ... )
        >>> F = SigmaAlgebra(sample_space=Omega).from_dict(
        ...     {
        ...         0: 0,
        ...         1: 1,
        ...         2: 1,
        ...         3: 2,
        ...     }
        ... )
        >>> A = F.get_event([1, 2])
        >>> prob_space = ProbabilitySpace.from_event(
        ...     event=A, prob_measure=P, sig_algebra=F
        ... )
        >>> print(prob_space) # doctest: +NORMALIZE_WHITESPACE
        Probability space (A, F_A, P_A)
        ===============================
        <BLANKLINE>
        * Sample space 'A':
        [1, 2]
        <BLANKLINE>
        * Sigma algebra 'F_A':
                atom ID
        sample
        1             1
        2             1
        <BLANKLINE>
        * Probability measure 'P_A':
                probability
        sample
        1          0.416667
        2          0.583333

        Notes
        -----
        Let $A$ be an event in a probability space $(\Omega, \mathcal{F},P)$. Provided that $A$ has positive probability, we may construct a *conditional probability space* $(A, \mathcal{F}_A, P_A)$ as follows. The $\sigma$-algebra $\mathcal{F}_A$ contains those sets of the form $A\cap B$, for $B\in \mathcal{F}$. The probability measure $P_A$ is defined on events $E\in \mathcal{F}_A$ by setting $P_A(E) = P(E)/P(A)$.

        Provided that $\Omega$ is finite (as it always is, in SigAlg), then the $\sigma$-algebra $\mathcal{F}_A$ is determined uniquely by its atoms, which are just the nonempty intersections of the atoms of $\mathcal{F}$ with $A$. Thus, the same atom identifiers from $\mathcal{F}$ can be used to define $\mathcal{F}_A$.
        """
        from ..probability_measures.probability_measure import ProbabilityMeasure
        from ..sigma_algebras.sigma_algebra import SigmaAlgebra
        from .event import Event

        if not isinstance(event, Event):
            raise TypeError("event must be an Event instance.")
        if not isinstance(prob_measure, ProbabilityMeasure):
            raise TypeError("prob_measure must be a ProbabilityMeasure instance.")
        if sig_algebra is not None and not isinstance(sig_algebra, SigmaAlgebra):
            raise TypeError("sig_alg must be a SigmaAlgebra instance.")
        if prob_measure.sample_space != event.sample_space:
            raise ValueError(
                "The probability measure must be defined on the same sample space as the event."
            )
        if sig_algebra is not None and sig_algebra.sample_space != event.sample_space:
            raise ValueError(
                "If given, the sigma-algebra must be defined on the same sample space as the event."
            )

        prob_event = prob_measure(event)
        event_sample_space = event.to_sample_space()

        if prob_event < 1e-8:
            raise ValueError(
                "Cannot create a probability space from an event with 0 probability."
            )
        if event.name is not None and prob_measure.name is not None:
            prob_measure_name = f"{prob_measure.name}_{event.name}"
        else:
            prob_measure_name = "prob_event"
        data = prob_measure.data.loc[event] / prob_event

        if sig_algebra is not None:
            if event not in sig_algebra:
                raise ValueError("If given, the event must be in the sigma-algebra.")
            event_atom_ids = {
                omega: sig_algebra.sample_id_to_atom_id[omega] for omega in event
            }
            if event.name is not None and sig_algebra.name is not None:
                sig_alg_measure_name = f"{sig_algebra.name}_{event.name}"
            else:
                sig_alg_measure_name = "sigma-algebra_event"
            event_sigma_algebra = SigmaAlgebra(
                sample_space=event_sample_space, name=sig_alg_measure_name
            ).from_dict(event_atom_ids)
        else:
            event_sigma_algebra = SigmaAlgebra.power_set(
                sample_space=event_sample_space
            )

        event_probability_measure = ProbabilityMeasure(
            sig_alg=event_sigma_algebra, name=prob_measure_name
        ).from_pandas(data)

        return cls(
            sample_space=event_sample_space,
            sig_alg=event_sigma_algebra,
            prob_measure=event_probability_measure,
        )

    # --------------------- methods --------------------- #

    def sample(
        self, size: int = 1, random_state: int | np.random.Generator | None = None
    ) -> list[Hashable]:
        """Generate random samples from this probability space.

        Parameters
        ----------
        size : int, default=1
            Number of samples to generate. Must be positive.
        random_state : int | np.random.Generator | None, default=None
            Random seed or generator for reproducibility. If `None`, the random state is not set.

        Returns
        -------
        sample : list[Hashable]
            A list of sampled outcomes from the sample space.

        Raises
        ------
        ValueError
            If `size` is not a positive integer.
        TypeError
            If `random_state` is not an integer, `np.random.Generator`, or `None`.

        Examples
        --------
        >>> import numpy as np
        >>> from sigalg.core import ProbabilityMeasure, ProbabilitySpace, SampleSpace
        >>> Omega = SampleSpace().from_sequence(size=4)
        >>> P = ProbabilityMeasure(sample_space=Omega).from_dict(
        ...     {
        ...         0: 0.15,
        ...         1: 0.25,
        ...         2: 0.35,
        ...         3: 0.25,
        ...     }
        ... )
        >>> prob_space = ProbabilitySpace(sample_space=Omega, prob_measure=P)
        >>> rng = np.random.default_rng(seed=42)
        >>> sample = prob_space.sample(size=5, random_state=rng)
        >>> print(sample)
        [3, 2, 3, 2, 0]
        """
        if not isinstance(size, int) or size < 1:
            raise ValueError("size must be a positive integer.")
        if random_state is not None and not isinstance(
            random_state, (int, np.random.Generator)
        ):
            raise TypeError(
                "random_state must be an integer, np.random.Generator, or None."
            )

        if isinstance(random_state, np.random.Generator):
            rng = random_state
        elif isinstance(random_state, int):
            rng = np.random.default_rng(random_state)
        else:
            rng = np.random.default_rng()

        outcomes = list(self.sample_space)
        probabilities = [self.prob_measure(outcome) for outcome in outcomes]

        samples = rng.choice(outcomes, size=size, p=probabilities)

        return samples.tolist()

    # --------------------- data access methods --------------------- #

    def __iter__(self):
        """Allow unpacking of probability space components.

        Enables syntax like: `Omega, F, P = prob_space`, where `Omega` is the sample space of the probability space, and `F` and `P` are its sigma-algebra and probability measure, respectively.

        Yields
        ------
        sample_space : SampleSpace
            The sample space.
        sig_alg : SigmaAlgebra
            The sigma-algebra.
        prob_measure : ProbabilityMeasure
            The probability measure.
        """
        yield self.sample_space
        yield self.sig_alg
        yield self.prob_measure

    # --------------------- equality --------------------- #

    def __eq__(self, other: object) -> bool:
        """Check equality with another probability space.

        Two probability spaces are equal if they have the same sample space,
        sigma-algebra, and probability measure.

        Parameters
        ----------
        other : object
            Another object to compare with.

        Returns
        -------
        is_equal : bool
            `True` if the other object is a `ProbabilitySpace` with identical
            components, `False` otherwise.
        """
        if not isinstance(other, ProbabilitySpace):
            return False
        return (
            self.sample_space == other.sample_space
            and self.sig_alg == other.sig_alg
            and self.prob_measure == other.prob_measure
        )

    # --------------------- representation --------------------- #

    def __repr__(self) -> str:
        """Return a concise string representation of the probability space.

        Returns
        -------
        repr_str : str
            A string representation showing the probability space's component names.
        """
        return (
            f"ProbabilitySpace("
            f"sample_space={self.sample_space.name}, "
            f"sig_alg={self.sig_alg.name}, "
            f"prob_measure={self.prob_measure.name})"
        )

    def __str__(self) -> str:
        """Return a detailed string representation of the probability space.

        Returns
        -------
        repr_str : str
            A formatted string showing the probability space header and detailed
            representations of its components.
        """
        header = (
            f"Probability space ("
            f"{self.sample_space.name}, "
            f"{self.sig_alg.name}, "
            f"{self.prob_measure.name})"
        )
        separator = "=" * len(header)
        return (
            header
            + "\n"
            + separator
            + "\n\n* "
            + repr(self.sample_space)
            + "\n\n* "
            + repr(self.sig_alg)
            + "\n\n* "
            + repr(self.prob_measure)
        )

    # --------------------- validation methods --------------------- #

    @staticmethod
    def _validate_parameters(
        sample_space: SampleSpace,
        sig_alg: SigmaAlgebra | None,
        prob_measure: ProbabilityMeasure | None,
    ) -> None:
        """Validate probability space construction parameters.

        Parameters
        ----------
        sample_space : SampleSpace
            The sample space to validate.
        sig_alg : SigmaAlgebra or None
            The sigma-algebra to validate.
        prob_measure : ProbabilityMeasure or None
            The probability measure to validate.

        Raises
        ------
        TypeError
            If `sample_space` is not a `SampleSpace` instance, `sig_algebra` is not
            a `SigmaAlgebra` instance (when provided), or `prob_measure` is
            not a `ProbabilityMeasure` instance (when provided).
        ValueError
            If `sig_alg` or `prob_measure` have sample spaces that do
            not match the provided `sample_space`.
        """
        from ..probability_measures import ProbabilityMeasure
        from ..sigma_algebras import SigmaAlgebra
        from .sample_space import SampleSpace

        if not isinstance(sample_space, SampleSpace):
            raise TypeError("sample_space must be a SampleSpace instance.")
        if sig_alg is not None and not isinstance(sig_alg, SigmaAlgebra):
            raise TypeError("sig_alg must be a SigmaAlgebra instance.")
        if prob_measure is not None and not isinstance(
            prob_measure, ProbabilityMeasure
        ):
            raise TypeError("prob_measure must be a ProbabilityMeasure instance.")
        if sig_alg is not None and sig_alg.sample_space != sample_space:
            raise ValueError("sig_alg must be defined on the given sample_space.")
        if prob_measure is not None and prob_measure.sample_space != sample_space:
            raise ValueError("prob_measure must be defined on the given sample_space.")
