site_name: sigalg v0.1.1

theme:
  name: material
  favicon: assets/favicon-1.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - toc.integrate
    - toc.follow
  palette: 
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  icon:
    repo: fontawesome/brands/git

nav:
  - Home: index.md
  - Getting Started: getting_started/index.md
  - Code Snippets: code_snippets/index.md
  - API Reference:
      - Overview: api/index.md
      - Core: api/core.md
      - L^2 Spaces: api/l2.md
      - Stochastic Processes: api/processes.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../src]
          options:
            docstring_style: numpy
            show_source: false
            show_root_heading: true
            show_root_full_path: false
            separate_signature: true

markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      check_paths: true
      base_path: docs/code_snippets/scripts

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6

extra_css:
  - stylesheets/extra.css
  
extra:
  social:
    - icon: fontawesome/brands/git
      link: https://github.com/jmyers7/sigalg
      name: GitHub
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/sigalg
      name: PyPI
  
repo_url: https://github.com/jmyers7/sigalg
repo_name: jmyers7/sigalg