"""A class representing a Markov chain stochastic process."""

from __future__ import annotations

from itertools import product
from typing import TYPE_CHECKING, Literal

import numpy as np
import pandas as pd

from ..base.stochastic_process import StochasticProcess, generator

if TYPE_CHECKING:
    from collections.abc import Hashable

    from numpy.typing import ArrayLike

    from ...core.measures.parametrized_probability_measure import (
        ParametrizedProbabilityMeasure,
    )
    from ...core.measures.probability_measure import ProbabilityMeasure
    from ...core.spaces.domain import Domain
    from ...typing.index_like import IndexLike


# TODO: add Notes section
# TODO: add custom __repr__ method
class MarkovChain(StochasticProcess):
    """A class representing a Markov chain stochastic process.

    The constructor is not intended for direct usage. Instead, user's should call the `generate` class method. See the Examples section below.

    See the Notes section below for the mathematical details.

    Examples
    --------
    >>> import numpy as np
    >>> from sigalg.core import (
    ...     Domain,
    ...     ParametrizedProbabilityMeasure,
    ...     ProbabilityMeasure,
    ... )
    >>> from sigalg.processes import MarkovChain

    Exhaustively enumerate all trajectories of an order-2 Markov chain of length 2 on a binary state space. The initial distribution and transition kernel are instances of `ProbabilityMeasure` and `ParametrizedProbabilityMeasure`, respectively.

    >>> S = Domain.from_sequence(size=2, variable_name="s", name="S")
    >>> S_0 = Domain.from_sequence(size=2, variable_name="s_0", name="S_0")
    >>> pi = ProbabilityMeasure(domain=S, mapping={0: 0.2, 1: 0.8}, name="pi")
    >>> K = ParametrizedProbabilityMeasure.from_domains(
    ...     measure_domain=S,
    ...     parameter_domain=S_0,
    ...     mapping={
    ...         (0, 0): 0.4,
    ...         (0, 1): 0.6,
    ...         (1, 0): 0.7,
    ...         (1, 1): 0.3,
    ...     },
    ...     name="K",
    ... )
    >>> X = MarkovChain.generate(
    ...     kernel=K,
    ...     initial_distribution=pi,
    ...     mode="enum",
    ...     length=2,
    ... )
    >>> print(X)  # doctest: +NORMALIZE_WHITESPACE
    Markov chain 'X':
    t      0  1  2
    omega
    0      0  0  0
    1      0  0  1
    2      0  1  0
    3      0  1  1
    4      1  0  0
    5      1  0  1
    6      1  1  0
    7      1  1  1

    Check that the joint distribution factors according to the Markov property.

    >>> P = X.measure
    >>> np.allclose(
    ...     P >> X, (P >> X[0]) * (P.conditional(X[0]) >> X[1]) * (P.conditional(X[1]) >> X[2])
    ... )
    True

    Markov chains may also be generated by passing array-like objects for the initial distribution and transition kernel.

    >>> Y = MarkovChain.generate(
    ...     kernel=[[0.4, 0.6], [0.7, 0.3]],
    ...     initial_distribution=[0.2, 0.8],
    ...     mode="enum",
    ...     length=2,
    ...     name="Y",
    ... )
    >>> print(Y)  # doctest: +NORMALIZE_WHITESPACE
    Markov chain 'Y':
    t      0  1  2
    omega
    0      0  0  0
    1      0  0  1
    2      0  1  0
    3      0  1  1
    4      1  0  0
    5      1  0  1
    6      1  1  0
    7      1  1  1

    Exhaustively enumerate all trajectories of an order-3 Markov chain of length 3 on a binary state space. The initial distribution and transition kernel are randomly generated instances of `ProbabilityMeasure` and `ParametrizedProbabilityMeasure`, respectively. Note, however, that the initial distribution is defined on the second Cartesian power of the state space and the transition kernel is represented by a rank-3 tensor.

    >>> rng = np.random.default_rng(42)
    >>> pi = ProbabilityMeasure.from_rand(
    ...     domain=S ^ 2,
    ...     name="pi",
    ...     random_state=rng,
    ... )
    >>> K = ParametrizedProbabilityMeasure.from_rand(
    ...     measure_domain=S,
    ...     parameter_domain=S ^ 2,
    ...     random_state=rng,
    ... )
    >>> Z = MarkovChain.generate(
    ...     kernel=K,
    ...     initial_distribution=pi,
    ...     mode="enum",
    ...     length=3,
    ...     name="Z",
    ... )
    >>> print(Z)  # doctest: +NORMALIZE_WHITESPACE
    Markov chain 'Z':
    t       0  1  2  3
    omega
    0       0  0  0  0
    1       0  0  0  1
    2       0  0  1  0
    3       0  0  1  1
    4       0  1  0  0
    5       0  1  0  1
    6       0  1  1  0
    7       0  1  1  1
    8       1  0  0  0
    9       1  0  0  1
    10      1  0  1  0
    11      1  0  1  1
    12      1  1  0  0
    13      1  1  0  1
    14      1  1  1  0
    15      1  1  1  1

    Check that the joint distribution factors according to the order-3 Markov property.

    >>> Q = Z.measure.with_name("Q")
    >>> np.allclose(
    ...     Q >> Z,
    ...     (Q >> Z[0, 1])
    ...     * (Q.conditional(Z[0, 1]) >> Z[2])
    ...     * (Q.conditional(Z[1, 2]) >> Z[3]),
    ... )
    True
    """

    _repr_name = "MarkovChain"
    _str_name = "Markov chain"

    # --------------------- constructors --------------------- #

    @generator
    def generate(
        cls,
        kernel: ArrayLike | ParametrizedProbabilityMeasure,
        initial_distribution: ArrayLike | ProbabilityMeasure,
        mode: Literal["enum", "sim"] = "sim",
        n_trajectories: int | None = None,
        domain_name: Hashable | None = None,
        index: IndexLike | None = None,
        length: int | None = None,
        name: Hashable = "X",
        random_state: int | np.random.Generator | None = None,
    ) -> dict[str, object]:
        """Generate trajectories of the Markov chain by either exhaustive enumeration or Monte Carlo simulation.

        Parameters
        ----------
        kernel : ArrayLike | ParametrizedProbabilityMeasure
            Either a parametrized probability measure the transition kernel or an object that can be coerced into a transition tensor (i.e., a multi-dimensional numpy array).
        initial_distribution : ArrayLike | ProbabilityMeasure
            Either a probability measure representing the initial distribution or an object that can be coerced into a probability tensor (i.e., a multi-dimensional numpy array).
        mode : Literal["enum", "sim"], default="sim"
            Whether to generate trajectories by exhaustive enumeration or Monte Carlo simulation.
        n_trajectories : int | None, default=None
            The number of trajectories to simulate. If the generation mode is set to `enum`, this parameter is ignored.
        domain_name : Hashable | None, default=None
            The name of the domain. If `None`, a default will be generated.
        index : IndexLike | None, default=None
            The index of the stochastic process. One of `index` or `length` must be provided; if both are provided, the length of `index` must match `length`.
        length : int | None, default=None
            The length of the trajectories of the stochastic process. One of `index` or `length` must be provided; if both are provided, the length of `index` must match `length`.
        name : Hashable, default="X"
            The name of the stochastic process.
        random_state : int | np.random.Generator | None, default=None
            An optional random state for reproducibility.

        Returns
        -------
        info : dict[str, object]
            A dictionary containing the names of the MarkovChain-specific parameters and their values.

        Examples
        --------
        >>> import numpy as np
        >>> from sigalg.core import (
        ...     Domain,
        ...     ParametrizedProbabilityMeasure,
        ...     ProbabilityMeasure,
        ... )
        >>> from sigalg.processes import MarkovChain

        Exhaustively enumerate all trajectories of an order-2 Markov chain of length 2 on a binary state space. The initial distribution and transition kernel are instances of `ProbabilityMeasure` and `ParametrizedProbabilityMeasure`, respectively.

        >>> S = Domain.from_sequence(size=2, variable_name="s", name="S")
        >>> S_0 = Domain.from_sequence(size=2, variable_name="s_0", name="S_0")
        >>> pi = ProbabilityMeasure(domain=S, mapping={0: 0.2, 1: 0.8}, name="pi")
        >>> K = ParametrizedProbabilityMeasure.from_domains(
        ...     measure_domain=S,
        ...     parameter_domain=S_0,
        ...     mapping={
        ...         (0, 0): 0.4,
        ...         (0, 1): 0.6,
        ...         (1, 0): 0.7,
        ...         (1, 1): 0.3,
        ...     },
        ...     name="K",
        ... )
        >>> X = MarkovChain.generate(
        ...     kernel=K,
        ...     initial_distribution=pi,
        ...     mode="enum",
        ...     length=2,
        ... )
        >>> print(X)  # doctest: +NORMALIZE_WHITESPACE
        Markov chain 'X':
        t      0  1  2
        omega
        0      0  0  0
        1      0  0  1
        2      0  1  0
        3      0  1  1
        4      1  0  0
        5      1  0  1
        6      1  1  0
        7      1  1  1

        Check that the joint distribution factors according to the Markov property.

        >>> P = X.measure
        >>> np.allclose(
        ...     P >> X, (P >> X[0]) * (P.conditional(X[0]) >> X[1]) * (P.conditional(X[1]) >> X[2])
        ... )
        True

        Markov chains may also be generated by passing array-like objects for the initial distribution and transition kernel.

        >>> Y = MarkovChain.generate(
        ...     kernel=[[0.4, 0.6], [0.7, 0.3]],
        ...     initial_distribution=[0.2, 0.8],
        ...     mode="enum",
        ...     length=2,
        ...     name="Y",
        ... )
        >>> print(Y)  # doctest: +NORMALIZE_WHITESPACE
        Markov chain 'Y':
        t      0  1  2
        omega
        0      0  0  0
        1      0  0  1
        2      0  1  0
        3      0  1  1
        4      1  0  0
        5      1  0  1
        6      1  1  0
        7      1  1  1

        Exhaustively enumerate all trajectories of an order-3 Markov chain of length 3 on a binary state space. The initial distribution and transition kernel are randomly generated instances of `ProbabilityMeasure` and `ParametrizedProbabilityMeasure`, respectively. Note, however, that the initial distribution is defined on the second Cartesian power of the state space and the transition kernel is represented by a rank-3 tensor.

        >>> rng = np.random.default_rng(42)
        >>> pi = ProbabilityMeasure.from_rand(
        ...     domain=S ^ 2,
        ...     name="pi",
        ...     random_state=rng,
        ... )
        >>> K = ParametrizedProbabilityMeasure.from_rand(
        ...     measure_domain=S,
        ...     parameter_domain=S ^ 2,
        ...     random_state=rng,
        ... )
        >>> Z = MarkovChain.generate(
        ...     kernel=K,
        ...     initial_distribution=pi,
        ...     mode="enum",
        ...     length=3,
        ...     name="Z",
        ... )
        >>> print(Z)  # doctest: +NORMALIZE_WHITESPACE
        Markov chain 'Z':
        t       0  1  2  3
        omega
        0       0  0  0  0
        1       0  0  0  1
        2       0  0  1  0
        3       0  0  1  1
        4       0  1  0  0
        5       0  1  0  1
        6       0  1  1  0
        7       0  1  1  1
        8       1  0  0  0
        9       1  0  0  1
        10      1  0  1  0
        11      1  0  1  1
        12      1  1  0  0
        13      1  1  0  1
        14      1  1  1  0
        15      1  1  1  1

        Check that the joint distribution factors according to the order-3 Markov property.

        >>> Q = Z.measure.with_name("Q")
        >>> np.allclose(
        ...     Q >> Z,
        ...     (Q >> Z[0, 1])
        ...     * (Q.conditional(Z[0, 1]) >> Z[2])
        ...     * (Q.conditional(Z[1, 2]) >> Z[3]),
        ... )
        True
        """
        from ...core.measures.parametrized_probability_measure import (
            ParametrizedProbabilityMeasure,
        )
        from ...core.measures.probability_measure import ProbabilityMeasure

        if isinstance(kernel, ParametrizedProbabilityMeasure):
            kernel = kernel.to_numpy(multi_dim=True)
        else:
            try:
                kernel = np.array(kernel)
            except Exception as e:
                raise TypeError("Failed to convert kernel to a numpy array.") from e
        if isinstance(initial_distribution, ProbabilityMeasure):
            initial_distribution = initial_distribution.to_numpy(
                multi_dim=initial_distribution.domain.dimension != 1
            )
        else:
            try:
                initial_distribution = np.array(initial_distribution)
            except Exception as e:
                raise TypeError(
                    "Failed to convert initial_distribution to a numpy array."
                ) from e

        order = initial_distribution.ndim
        n_states = initial_distribution.shape[0]

        if kernel.shape != (n_states,) * (order + 1):
            raise ValueError(
                "Each dimension of the kernel must have size equal to the number of states."
            )
        if initial_distribution.shape != (n_states,) * order:
            raise ValueError(
                "Each dimension of the initial distribution must have size equal to the number of states."
            )
        ones = np.ones(shape=(n_states,) * (order - 1))
        if not np.allclose(kernel.sum(axis=-1), ones):
            raise ValueError(
                "The sum of the transition probabilities for each state must be 1."
            )
        if not np.allclose(initial_distribution.sum(), ones):
            raise ValueError(
                "The sum of the probabilities in the initial distribution must be 1."
            )
        if not (kernel >= 0).all():
            raise ValueError("All transition probabilities must be non-negative.")
        if not (initial_distribution >= 0).all():
            raise ValueError(
                "All probabilities in the initial distribution must be non-negative."
            )

        return {
            "kernel": kernel,
            "initial_distribution": initial_distribution,
        }

    @classmethod
    def from_rand(
        cls,
        order: int = 1,
        n_states: int = 2,
        mode: Literal["enum", "sim"] = "sim",
        n_trajectories: int | None = None,
        domain_name: Hashable | None = None,
        index: IndexLike | None = None,
        length: int | None = None,
        name: Hashable = "X",
        random_state: int | np.random.Generator | None = None,
    ) -> MarkovChain:
        """Generate a random Markov chain.

        Parameters
        ----------
        order : int, default=1
            The order of the Markov chain.
        n_states : int, default=2
            The number of states of the Markov chain.
        mode : Literal["enum", "sim"], default="sim"
            Whether to generate trajectories by exhaustive enumeration or Monte Carlo simulation.
        n_trajectories : int | None, default=None
            The number of trajectories to simulate. If the generation mode is set to `enum`, this parameter is ignored.
        domain_name : Hashable | None, default=None
            The name of the domain. If `None`, a default will be generated.
        index : IndexLike | None, default=None
            The index of the stochastic process. One of `index` or `length` must be provided; if both are provided, the length of `index` must match `length`.
        length : int | None, default=None
            The length of the trajectories of the stochastic process. One of `index` or `length` must be provided; if both are provided, the length of `index` must match `length`.
        name : Hashable, default="X"
            The name of the stochastic process.
        random_state : int | np.random.Generator | None, default=None
            An optional random state for reproducibility.

        Returns
        -------
        mc : MarkovChain
            A randomly generated Markov chain.

        Examples
        --------
        >>> import numpy as np
        >>> from sigalg.processes import MarkovChain
        >>> rng = np.random.default_rng(42)

        Exhaustively generate all trajectories of an order-3 Markov chain of length 5.

        >>> X = MarkovChain.from_rand(
        ...     order=3,
        ...     n_states=3,
        ...     mode="enum",
        ...     length=5,
        ...     random_state=rng,
        ... )
        >>> print(X)  # doctest: +NORMALIZE_WHITESPACE
        Markov chain 'X':
        t      0  1  2  3  4  5
        omega
        0      0  0  0  0  0  0
        1      0  0  0  0  0  1
        2      0  0  0  0  0  2
        3      0  0  0  0  1  0
        4      0  0  0  0  1  1
        ...   .. .. .. .. .. ..
        724    2  2  2  2  1  1
        725    2  2  2  2  1  2
        726    2  2  2  2  2  0
        727    2  2  2  2  2  1
        728    2  2  2  2  2  2
        <BLANKLINE>
        [729 rows x 6 columns]

        Check that the joint probability measure factors according to the Markov property.

        >>> P = X.measure
        >>> np.allclose(
        ...     P >> X,
        ...     (P >> X[0, 1, 2])
        ...     * (P.conditional(X[0, 1, 2]) >> X[3])
        ...     * (P.conditional(X[1, 2, 3]) >> X[4])
        ...     * (P.conditional(X[2, 3, 4]) >> X[5]),
        ... )
        True
        """
        rng = (
            random_state
            if isinstance(random_state, np.random.Generator)
            else np.random.default_rng(random_state)
        )

        kernel = rng.dirichlet(alpha=(1,) * n_states, size=(n_states,) * order)
        initial_distribution = rng.dirichlet(
            alpha=(1,) * (n_states**order), size=1
        ).reshape((n_states,) * order)

        return cls.generate(
            kernel=kernel,
            initial_distribution=initial_distribution,
            mode=mode,
            n_trajectories=n_trajectories,
            domain_name=domain_name,
            index=index,
            length=length,
            name=name,
            random_state=rng,
        )

    # --------------------- properties --------------------- #

    @property
    def kernel(self) -> np.ndarray:
        """The transition tensor (kernel) of the Markov chain.

        Returns
        -------
        transition_matrix : np.ndarray
            The transition tensor (kernel) of the Markov chain.

        Examples
        --------
        >>> import numpy as np
        >>> from sigalg.processes import MarkovChain
        >>> rng = np.random.default_rng(42)

        Generate a random Markov chain of order 3 and length 5.

        >>> X = MarkovChain.from_rand(
        ...     order=3,
        ...     n_states=3,
        ...     mode="enum",
        ...     length=5,
        ...     random_state=rng,
        ... )

        Print the shape of the transition tensor.

        >>> X.kernel.shape
        (3, 3, 3, 3)
        """
        return self._kernel

    @property
    def initial_distribution(self) -> np.ndarray:
        """The initial distribution of the Markov chain as a NumPy array.

        Returns
        -------
        initial_distribution : np.ndarray
            The initial distribution of the Markov chain.

        Examples
        --------
        >>> import numpy as np
        >>> from sigalg.processes import MarkovChain
        >>> rng = np.random.default_rng(42)

        Generate a random Markov chain of order 3 and length 5.

        >>> X = MarkovChain.from_rand(
        ...     order=3,
        ...     n_states=3,
        ...     mode="enum",
        ...     length=5,
        ...     random_state=rng,
        ... )

        Print the shape of the initial distribution.

        >>> X.initial_distribution.shape
        (3, 3, 3)
        """
        return self._initial_distribution

    @property
    def order(self) -> int:
        """Get the order of the Markov chain.

        Returns
        -------
        order : int
            The order of the Markov chain.

        Examples
        --------
        >>> import numpy as np
        >>> from sigalg.processes import MarkovChain
        >>> rng = np.random.default_rng(42)

        Generate a random Markov chain of order 4 and length 5.

        >>> X = MarkovChain.from_rand(
        ...     order=4,
        ...     n_states=3,
        ...     mode="enum",
        ...     length=5,
        ...     random_state=rng,
        ... )

        Print the order of the Markov chain.

        >>> X.order
        4
        """
        return self.initial_distribution.ndim

    @property
    def state_space(self) -> np.ndarray:
        """Get the state space of the Markov chain.

        Returns
        -------
        state_space : np.ndarray
            An array representing the states of the Markov chain.
        """
        return np.array(range(len(self.initial_distribution)))

    @property
    def n_states(self) -> int:
        """Get the number of states in the Markov chain.

        Returns
        -------
        n_states : int
            The number of states in the Markov chain.

        Examples
        --------
        >>> import numpy as np
        >>> from sigalg.processes import MarkovChain
        >>> rng = np.random.default_rng(42)

        Generate a random Markov chain of order 4 and length 5.

        >>> X = MarkovChain.from_rand(
        ...     order=4,
        ...     n_states=3,
        ...     mode="enum",
        ...     length=5,
        ...     random_state=rng,
        ... )

        Print the number of states of the Markov chain.

        >>> X.n_states
        3
        """
        return self.initial_distribution.shape[0]

    # --------------------- enumeration methods --------------------- #

    def _enumeration_subclass_hook(self):
        """Hook for enumeration logic.

        Returns
        -------
        trajectories : pd.DataFrame
            A data frame containing the trajectories of the stochastic process.
        """  # noqa: D401
        trajectories = list(product(self.state_space, repeat=len(self._index)))
        return pd.DataFrame(data=trajectories, columns=self._index.data)

    def _generate_exact_prob_measure(self, domain: Domain) -> ProbabilityMeasure:
        """Generate the exact probability measure for an enumerated Markov chain.

        Returns
        -------
        prob_measure : ProbabilityMeasure
            The exact probability measure for the enumerated stochastic process.
        """
        from ...core.measures.probability_measure import ProbabilityMeasure

        trajectories = self.data.values

        initial_state_indices = trajectories[:, : self.order].T
        partial_traj_indices = [
            trajectories[:, i : i + self.length - self.order + 1]
            for i in range(self.order + 1)
        ]
        probs = self.initial_distribution[
            *initial_state_indices
        ].flatten() * self.kernel[*partial_traj_indices].prod(axis=-1)

        return ProbabilityMeasure(
            domain=domain,
            mapping=pd.Series(probs, index=domain.data),
        )

    # --------------------- simulation methods --------------------- #

    def _simulation_subclass_hook(self) -> pd.DataFrame:
        """Generate simulated data for the Markov chain.

        Returns
        -------
        trajectories : pd.DataFrame
            A DataFrame containing the simulated trajectories as rows and time points as columns.
        """
        possible_initial_states = np.array(
            list(product(self.state_space, repeat=self.order))
        )
        initial_states = self.random_state.choice(
            possible_initial_states,
            size=self.n_trajectories,
            p=self.initial_distribution[*possible_initial_states.T],
        )

        length = len(self._index)

        trajectories = np.empty(shape=(self.n_trajectories, length), dtype=np.int64)
        trajectories[:, : self.order] = initial_states

        for t in range(length - self.order):
            p = self.kernel[*trajectories[:, t : t + self.order].T]
            cum = np.cumsum(p, axis=1)
            cum[:, -1] = 1.0
            u = self.random_state.uniform(size=(self.n_trajectories, 1))
            indices = (cum <= u).sum(axis=-1)
            trajectories[:, t + self.order] = self.state_space[indices]

        return pd.DataFrame(data=trajectories, columns=self._index.data)

    # --------------------- representation --------------------- #

    # def __repr__(self) -> str:
    #     """Return a concise string representation of the Markov chain.

    #     Returns
    #     -------
    #     repr_str : str
    #         The string representation of the Markov chain.
    #     """
    #     if self.data is None:
    #         return type(self)._repr_name + "(empty)"
    #     if self.measure is not None:
    #         return (
    #             type(self)._repr_name + f"(domain={self.domain.name}, "
    #             f"sig_alg={self.sig_alg.name}, "
    #             f"measure={self.measure.name}, "
    #             f"transition_matrix={self.transition_matrix.name}, "
    #             f"initial_distribution={self.initial_distribution.name}, "
    #             f"name={self.name})"
    #         )
