"""Demonstrate the attributes of random vectors and variables."""

from sigalg.core import ProbabilityMeasure, RandomVector, SampleSpace

Omega = SampleSpace().from_sequence(size=4)  # (1)!
outputs = dict(zip(Omega, [(1, 2), (1, 2), (3, 4), (5, 6)]))  # (2)!
X = RandomVector(domain=Omega).from_dict(outputs)
print(X, "\n")

print(f"The domain of 'X':\n{X.domain}\n")  # (3)!
print(f"The output dictionary of 'X':\n{X.outputs}\n")  # (4)!
print(f"The underlying data of 'X':\n{X.data}\n")  # (5)!

print("The component random variables of 'X':")  # (6)!
for component in X.components:
    print(component)
print("\n")

print(f"The name of 'X': {X.name}\n")  # (7)!
print(f"The index of 'X':\n{X.index}\n")  # (8)!
print(f"The sigma-algebra generated by 'X':\n{X.sigma_algebra}\n")  # (9)!

probs = dict(zip(Omega, [0.1, 0.1, 0.3, 0.5]))  # (10)!
P = ProbabilityMeasure(sample_space=Omega).from_dict(probs)
X.probability_measure = P
print(
    f"The probability measure of the probability space underlying 'X':\n{X.probability_measure}\n"
)

print(  # (11)!
    f"The range of 'X' as a probability space with the pushforward measure:\n{X.range}"
)
