name: Run tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        pandas-version: ["2.0.*", "2.3.*"]
        numpy-version: ["1.23.*", "2.3.*"]
        
        include:
          - os: macos-latest
            python-version: "3.13"
            pandas-version: "2.3.*"
            numpy-version: "2.3.*"
          
          - os: windows-latest
            python-version: "3.13"
            pandas-version: "2.3.*"
            numpy-version: "2.3.*"
      
      fail-fast: false

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==${{ matrix.numpy-version }}
          pip install pandas==${{ matrix.pandas-version }}
          pip install -e ".[dev]"

      - name: Display versions
        run: |
          python -c "import numpy; print(f'NumPy: {numpy.__version__}')"
          python -c "import pandas; print(f'Pandas: {pandas.__version__}')"

      - name: Run tests
        run: |
          pytest tests src --doctest-modules

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: matrix.python-version == '3.13' && matrix.pandas-version == '2.2.*' && matrix.numpy-version == '2.0.*' && matrix.os == 'ubuntu-latest'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml